<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Institution;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class HoiUsersSeeder extends Seeder
{
    public function run(): void
    {
        // Update admin email to production value
        DB::table('users')->where('email', 'admin@fde.edu.pk')->update(['email' => 'admin@fde.gov.pk']);
        $this->command->info('Admin email updated -> admin@fde.gov.pk');

        $password   = Hash::make('Test@1234');
        $seenEmails = [];
        $skipped    = [];
        $notFound   = [];
        $created    = 0;

        foreach ($this->getData() as $row) {
            $email = $row['email'];

            if (empty($email)) {
                $notFound[] = $row;
                continue;
            }

            if (isset($seenEmails[$email])) {
                $skipped[] = [
                    'email'         => $email,
                    'first_school'  => $seenEmails[$email],
                    'second_school' => $row['school'],
                    'second_emis'   => $row['emis'],
                ];
                continue;
            }
            $seenEmails[$email] = $row['school'];

            $institution = Institution::where('code', $row['emis'])->first();
            if (! $institution) {
                $notFound[] = $row;
                continue;
            }

            if (User::where('email', $email)->exists()) {
                continue;
            }

            $user = User::create([
                'name'           => $row['name'],
                'email'          => $email,
                'phone'          => $row['phone'],
                'password'       => $password,
                'institution_id' => $institution->id,
                'is_active'      => true,
            ]);
            $user->assignRole('hoi');
            $created++;
        }

        $this->command->info("Created: {$created} HoI accounts");

        if (count($skipped) > 0) {
            $this->command->warn("\nDuplicate emails skipped (" . count($skipped) . "):");
            $this->command->line(str_pad('Email', 42) . str_pad('First Occurrence (Created)', 58) . 'Second Occurrence (Skipped)');
            $this->command->line(str_repeat('-', 145));
            foreach ($skipped as $s) {
                $this->command->line(
                    str_pad($s['email'], 42) .
                    str_pad($s['first_school'], 58) .
                    "EMIS {$s['second_emis']} --- {$s['second_school']}"
                );
            }
        }

        if (count($notFound) > 0) {
            $this->command->warn("\nInstitution not found in DB (" . count($notFound) . "):");
            foreach ($notFound as $n) {
                $this->command->line("  EMIS {$n['emis']} --- {$n['school']}");
            }
        }
    }

    private function getData(): array
    {
        return [
            // Model Colleges
            ['emis' => '908', 'school' => 'ICB, G-6/3', 'name' => 'Prof. Dr. Yaseen Aafaqi', 'email' => 'icbedupk@gmail.com', 'phone' => '0333-5622902'],
            ['emis' => '905', 'school' => 'IMCB F-8/4', 'name' => 'Prof. Naeem ur Raheem', 'email' => 'rmbn_abn1@gmail.com', 'phone' => '0333-7447442'],
            ['emis' => '904', 'school' => 'IMCB F-7/3', 'name' => 'Dr. Rashid Ahmed Siddiqui', 'email' => 'risd08@gmail.com', 'phone' => '0321-5611855'],
            ['emis' => '906', 'school' => 'IMCB G-10/4', 'name' => 'Prof. Prof. M. Ihsan Ul Haq', 'email' => 'imcb260@gmail.com', 'phone' => '0334-5440689'],
            ['emis' => '901', 'school' => 'IMCB F-10/3', 'name' => 'Prof. Najeeb Ullah', 'email' => 'najeeb.anjum@gmail.com', 'phone' => '0333-5446675'],
            ['emis' => '909', 'school' => 'IMCB I-10/1', 'name' => 'Prof. M. Saeed', 'email' => 'msaeedimcb@gmail.com', 'phone' => '0316-5954771'],
            ['emis' => '910', 'school' => 'IMCB I-8/3', 'name' => 'Prof. Shahid Mehmood Abbasi', 'email' => 'shahidabbasi61@gmail.com', 'phone' => '0300-5011394'],
            ['emis' => '902', 'school' => 'IMCB F-11/1', 'name' => 'Prof. Ghayoor Hussain', 'email' => 'ghayoorhussain66@gmail.com', 'phone' => '0300-5173212'],
            ['emis' => '907', 'school' => 'IMCB G-11/1', 'name' => 'Prof. Amir Mumtaz', 'email' => 'amermumtaz74@gmail.com', 'phone' => '0333-5139238'],
            ['emis' => '925', 'school' => 'IMCB Pak. Town', 'name' => 'Prof. Sharafat Ali Awan', 'email' => 'maliksharafatali76@gmail.com', 'phone' => '0331-5003363'],
            ['emis' => '923', 'school' => 'IMCB G-13/2', 'name' => 'Prof. M. Riaz Hussain', 'email' => 'imcbddog13@gmail.com', 'phone' => '0333-5125081'],
            ['emis' => '924', 'school' => 'IMCB G-15', 'name' => 'Prof. Zahid Akbar', 'email' => 'prof.zahidakbar@gmail.com', 'phone' => '0333-5102142'],
            ['emis' => '926', 'school' => 'IMCB Maira Begwal', 'name' => 'Prof. Adnan Jahangir', 'email' => 'adnangehangirs@gamil.com', 'phone' => '0332-5142315'],
            ['emis' => '913', 'school' => 'ICG F-6/2', 'name' => 'Prof. Shazia Shamim', 'email' => 'shazia.shamim46@gmail.com', 'phone' => '0332-8500093'],
            ['emis' => '912', 'school' => 'IMCG F-6/2', 'name' => 'Prof. Aaliya Durrani', 'email' => 'imcgf62college@gmail.com', 'phone' => '0301-8730000'],
            ['emis' => '914', 'school' => 'IMCG F-7/4', 'name' => 'Dr. Sadia Aziz', 'email' => 'imcgf74@gmail.com', 'phone' => '0333-5396999'],
            ['emis' => '919', 'school' => 'IMCG F-10/2', 'name' => 'Prof. Fakhar uz Zia Kamal', 'email' => 'fakharbasharat@gmail.com', 'phone' => '0334-5334774'],
            ['emis' => '915', 'school' => 'IMCG F-8/1', 'name' => 'Prof. Aasia Rafiq', 'email' => 'islamabadcollegef.8@gmail.com', 'phone' => '0333-1520276'],
            ['emis' => '916', 'school' => 'IMCG G-10/2', 'name' => 'Prof. Saadat Begum', 'email' => 'saadatrathore@gmail.com', 'phone' => '0345-5174951'],
            ['emis' => '918', 'school' => 'IMCG I-8/4', 'name' => 'Prof. Shagufta Naz', 'email' => 'i84imcgibd@gmail.com', 'phone' => '0321-9399375'],
            ['emis' => '911', 'school' => 'IMCCG F-10/3', 'name' => 'Prof. Samra Latif', 'email' => 'samralatif9@gmail.com', 'phone' => '0331-5132146'],
            ['emis' => '917', 'school' => 'IMCG I-10/4', 'name' => 'Prof. Fatima Mobeen', 'email' => 'binaahmad03@gmail.com', 'phone' => '0333-5601711'],
            ['emis' => '920', 'school' => 'IMCG K. Town', 'name' => 'Prof. Dr. Munazza Fahim', 'email' => 'munazza_faheem68@yahoo.com', 'phone' => '0300-5393826'],
            ['emis' => '903', 'school' => 'IMCG F-11/3', 'name' => 'Prof. Rukhsana Naveed', 'email' => 'rukhsananaveed99@gmail.com', 'phone' => '0333-5174923'],
            ['emis' => '922', 'school' => 'IMCG G-13/1', 'name' => 'Prof. Saleha Tabassum', 'email' => 'tsaleha68@gmail.com', 'phone' => '0336-5276489'],
            ['emis' => '921', 'school' => 'IMCG G-14/4', 'name' => 'Prof. Musarrat Bokhari', 'email' => 'musarratbokhari789@gmail.com', 'phone' => '0335-9070529'],

            // EX-F.G. Colleges
            ['emis' => '802', 'school' => 'IMPC, H-8', 'name' => 'Prfo. Atthar ul Islam', 'email' => 'atharslam66@gmail.com', 'phone' => '0332-7942808'],
            ['emis' => '805', 'school' => 'IMPCC, H-8/4', 'name' => 'Prof. Dr. Muhammad Khalid', 'email' => 'khalildmuhammad07@gmail.com', 'phone' => '0333-5511561'],
            ['emis' => '804', 'school' => 'IMCB, H-9', 'name' => 'Prof. Muhammad Javed Iqbal', 'email' => 'principal.imcb.h9@gmail.com', 'phone' => '0300-9780372'],
            ['emis' => '803', 'school' => 'IMCB, F-10/4', 'name' => 'Mr. Muhammad Rashid', 'email' => 'saleemrashid@gmail.com', 'phone' => '0321-5106044'],
            ['emis' => '801', 'school' => 'IMCB, Sihala', 'name' => 'Mr. Zahoor Ahmed', 'email' => 'prof.zahoor@yahoo.com', 'phone' => '0334-5856956'],
            ['emis' => '806', 'school' => 'IMCG (PG) F-7/2', 'name' => 'Prof. Dr. Fouzia Tanveer Sheikh', 'email' => 'imcgf72@gmail.com', 'phone' => '0333-5107474'],
            ['emis' => '810', 'school' => 'IMCG (PG) F-7/4', 'name' => 'Ms. Ayesha Kiyani', 'email' => 'ayeshiakayani@gmail.com', 'phone' => '0307-5555415'],
            ['emis' => '807', 'school' => 'IMCG (PG) G-10/4', 'name' => 'Prof. Sadia Ibrar', 'email' => 'sadiaibrar@hotmail.com', 'phone' => '0334-5164710'],
            ['emis' => '809', 'school' => 'IMCG, I-8/3', 'name' => 'Ms. Najam Un Nisa', 'email' => 'imcgislamabad@gmail.com', 'phone' => '0333-3601098'],
            ['emis' => '811', 'school' => 'IMCG, I-14/3', 'name' => 'Ms. Shazia Wazir', 'email' => 'shaziawazir.ap@gmail.com', 'phone' => '0332-5137674'],
            ['emis' => '808', 'school' => 'IMCG, Humak', 'name' => 'Dr. Humaira Jabeen', 'email' => 'jabeen.h00@gmail.com', 'phone' => '0312-5281522'],
            ['emis' => '812', 'school' => 'IMCG, Bharakau', 'name' => 'Ms. Abida Parveen', 'email' => 'abidakalwar@gmail.com', 'phone' => '0333-7241916'],
            ['emis' => '813', 'school' => 'Home Economics College F-11/1', 'name' => 'Prof. Rozina Faheem', 'email' => 'rozina.faheem@yahoo.com', 'phone' => '0300-5098602'],

            // Urban-I
            ['emis' => '201', 'school' => 'IMCG G.6/1.4 IBD', 'name' => 'MS SAIRA MALIK', 'email' => 'maliksaira118@gmail.com', 'phone' => '3325200282'],
            ['emis' => '202', 'school' => 'IMSG(VI-X) G-6/1-3', 'name' => 'Shahida Jabeen Abbasi', 'email' => 'shahida.abbasig92@gmail.com', 'phone' => '0333-5112444'],
            ['emis' => '203', 'school' => 'IMS I-V G 61/1', 'name' => 'Shazia Ashraf', 'email' => 'shazia.ashraf789@gmail.com', 'phone' => '3335376274'],
            ['emis' => '204', 'school' => 'IMS (I-V) G-6/1-3', 'name' => 'Saeeda Fazal', 'email' => 'saeda.fazal@gmail.com', 'phone' => '3335268214'],
            ['emis' => '205', 'school' => 'IMS(I-VIII)G-6/1-4', 'name' => 'Humaa Bashir kayani', 'email' => 'khumaa73@gmail.com', 'phone' => '3369303796'],
            ['emis' => '206', 'school' => '8MS(I-V), G-6/4', 'name' => 'Shagufta Tayyab', 'email' => 'shaguftatayyab067@gmail.com', 'phone' => '3345013217'],
            ['emis' => '207', 'school' => 'IMSG(VI-X),G-6/2', 'name' => 'Asifa Nasim', 'email' => 'asifakhurram786@gmail.com', 'phone' => '3325509193'],
            ['emis' => '208', 'school' => 'IMS( I-V) G-6/2', 'name' => 'Samreen Jamal', 'email' => 'samreen773@gmail.com', 'phone' => '3334530428'],
            ['emis' => '209', 'school' => 'IMSG I-VIII G-6/2', 'name' => 'Attiya Perveen', 'email' => 'attiyaperveen1968@gmail.com', 'phone' => '3214608600'],
            ['emis' => '210', 'school' => 'IMS (I_V)HLR G_6/2', 'name' => 'Alia Masood', 'email' => 'aliaashfaque@gmail.com', 'phone' => '3341510562'],
            ['emis' => '211', 'school' => 'IMSG 1-10 PE G5', 'name' => 'Fauzia Tariq', 'email' => 'tariqfauzia99@gmail.com', 'phone' => '3005212945'],
            ['emis' => '212', 'school' => 'IMS (I-V), G-6/1-2', 'name' => 'AFSHAN FAAROOQ', 'email' => 'afshanfarooq7@gmail.com', 'phone' => '3379740318'],
            ['emis' => '213', 'school' => 'IMSG (VI-X) G-7/1 IBD', 'name' => 'Aliya Sadaf', 'email' => 'aliyasadafnp@gmail.com', 'phone' => '3348778848'],
            ['emis' => '214', 'school' => 'IMSG(VI-X) G7/2', 'name' => 'Bushra Jabeen', 'email' => 'bushrapms@gmail.com', 'phone' => '3215682285'],
            ['emis' => '215', 'school' => 'IMSG(i_viii)G7/3_2 islamabad', 'name' => 'Rukhsana Shahid', 'email' => 'shahidakbar107@email.com', 'phone' => '34553875044'],
            ['emis' => '216', 'school' => 'IMS(1-5)G-7/1', 'name' => 'UME FARWA(acting head)', 'email' => 'umefarwa2015@gmail.come', 'phone' => '3025129873'],
            ['emis' => '217', 'school' => 'IMS(I-V)G-7/4', 'name' => 'HUMA YASIN', 'email' => 'humayasin7@gmail.com', 'phone' => '3009869403'],
            ['emis' => '218', 'school' => 'IMSG (I-VIII) G-7/3-4', 'name' => 'Zahida Parveen', 'email' => 'zahidap479@gmail.com', 'phone' => '3335233000'],
            ['emis' => '219', 'school' => 'IMS (l-V),G-7/3-1', 'name' => 'Sharmeen Zaidi', 'email' => 'syeda.sharmeensohail@gmail.com', 'phone' => '0333-5502435'],
            ['emis' => '220', 'school' => 'IMS(I-V),G-7/3-3', 'name' => 'Ms.Sadia Hanif', 'email' => 'sadia.hanif38@gmail.com', 'phone' => '3335669253'],
            ['emis' => '221', 'school' => 'IMSG (I-VIII),F-7/1, Islamabad', 'name' => 'Shabnam Afreen', 'email' => 'ims1to8f71@gmail.com', 'phone' => '0300-8306885'],
            ['emis' => '222', 'school' => 'IMS i-v no I G-7/ 2', 'name' => 'Farkhanda Jabeen Lodhi', 'email' => 'farkhanda.lodhi@gmail.com', 'phone' => '3348538620'],
            ['emis' => '223', 'school' => 'IMSG (VI-X) F-7/2, IBD', 'name' => 'Amara Awais Niazi', 'email' => 'amara.awais@yahoo.com', 'phone' => '3215300252'],
            ['emis' => '224', 'school' => 'IMSG VI_X F 6/1', 'name' => 'Nusrat yasmin', 'email' => 'nusratyasmin80@gmail.com', 'phone' => '0332_1508237'],
            ['emis' => '225', 'school' => 'IMSG(I-VIII), F-7/4, Islamabad', 'name' => 'Saima Shaukat', 'email' => 'saimashaukat269@gmail.com', 'phone' => '3355499777'],
            ['emis' => '226', 'school' => 'IMS (I-V) F-6/ 4', 'name' => 'Bushra Shahid', 'email' => 'baaesbutt@gmail.com', 'phone' => '3335923333'],
            ['emis' => '227', 'school' => 'IMSG P-M ColonyG-5', 'name' => 'Fauzia Abbass', 'email' => 'fauzia.abbass68@gmail.com', 'phone' => '3125816343'],
            ['emis' => '228', 'school' => 'IMS (I-V), F-6/1', 'name' => 'Rukhsana Afzal', 'email' => 'rukhafzal2012@gmail.com', 'phone' => '3245271095'],
            ['emis' => '229', 'school' => 'IMS (I-VIII) F-6/3', 'name' => 'Naureen Sarwar', 'email' => 'noureensarwar123@gmail.com', 'phone' => '3000393141'],
            ['emis' => '230', 'school' => 'IMS(I-V) F-7/2-4', 'name' => 'Munazza Bibi', 'email' => 'munazza.bibi73@gmail.com', 'phone' => '3335946646'],
            ['emis' => '231', 'school' => 'IMS(I-V)F-7/2', 'name' => 'Rabia Qayyum', 'email' => 'rabiaqayyum21@gmail.com', 'phone' => '3339293281'],
            ['emis' => '232', 'school' => 'IMSB PM STAFF colony G-5 Islamabad', 'name' => 'Mohsin Raza', 'email' => 'mohsin.razano1@gmail.com', 'phone' => '3435800157'],
            ['emis' => '233', 'school' => 'IMSG (VI-X), E-8/3, IBD', 'name' => 'Mrs. PARVEEN AKHTAR', 'email' => 'imcge8.3@gmail.com', 'phone' => '+92 331 5374360'],
            ['emis' => '234', 'school' => 'IMS(I-V)NO1.E8.IBD', 'name' => 'Shaban Farrukh', 'email' => 'shabananoureen4@gmail.com', 'phone' => '333519415'],
            ['emis' => '235', 'school' => 'IMS(I-V) No.2 E-8/1', 'name' => 'Anjum Saqlain kiyani', 'email' => 'anjumsaqlainkayani@gmail.com', 'phone' => '3379823884'],
            ['emis' => '236', 'school' => 'IMSG(i-x)E-9', 'name' => 'Aliazareen', 'email' => 'aliazareen12@gmail.com', 'phone' => '3305940914'],
            ['emis' => '237', 'school' => 'IMS ( I-V), E-7 ISLAMABAD', 'name' => 'SAMINA SAEED', 'email' => 'ninasaeed2015@gmail.com', 'phone' => '0333 5149922'],
            ['emis' => '238', 'school' => 'IMCG G-8 4 IBD', 'name' => 'Ms Musarrat Sadiq', 'email' => 'musaratadil.edu@gmail.com', 'phone' => '+92 344 5916284'],
            ['emis' => '239', 'school' => 'IMSG Vi-X G-8/2', 'name' => 'Sajida bibi', 'email' => 'sajidaafridi378@gmail.com', 'phone' => '3325051683'],
            ['emis' => '240', 'school' => 'IMSG I-Vlll G8/ 4', 'name' => 'Mahwish Aftab', 'email' => 'mahwishaftab80@yahoo.com', 'phone' => '3033331313'],
            ['emis' => '241', 'school' => 'IMS( I-V) No1,G-8/4 IBD', 'name' => 'Farzana Anjum', 'email' => 'anjum221978@gmail.com', 'phone' => '0336-5307644'],
            ['emis' => '242', 'school' => 'IMS ( I - v) no 2, G - 8 /4', 'name' => 'Robina Sadiq', 'email' => 'robina.sadiq.15@gmail.com', 'phone' => '0300 5167749'],
            ['emis' => '243', 'school' => 'IMS (I-V)No.1 G-8/1', 'name' => 'Ayesha Bibi', 'email' => 'ayeshabibi880@gmail.com', 'phone' => '3485541610'],
            ['emis' => '244', 'school' => 'IMS( I-V) No.2, G-8/1', 'name' => 'Naila Naz', 'email' => 'nailanaz088@gmail.com', 'phone' => '3345069659'],
            ['emis' => '245', 'school' => 'IMS(1-V ) No 3 G-8/1', 'name' => 'Sajida Gulzar', 'email' => 'sajidagulzar1@gmail.com', 'phone' => '3335169655'],
            ['emis' => '246', 'school' => 'IMS(I-V) No 1, G-8/2', 'name' => 'Ms Amber Amir', 'email' => 'ambertahir2020@gmail.com', 'phone' => '0336-5351522'],
            ['emis' => '247', 'school' => 'IMS I-V NO 2 G-8/2', 'name' => 'Sabeen Malik', 'email' => 'sabeen1510@gmail.com', 'phone' => '3365355040'],
            ['emis' => '248', 'school' => 'IMS,I-V,PIMS,G-8/3', 'name' => 'FARIDA BEGUM', 'email' => 'faridabegum960@gmail.com', 'phone' => '0331-5536979'],
            ['emis' => '249', 'school' => 'IMS (I-V) F-8/2', 'name' => 'Hina Mukhtar', 'email' => 'hinamukhtare297@gmail.com', 'phone' => '3046797149'],
            ['emis' => '295', 'school' => 'IMS(1-5)#2 G 7/2', 'name' => 'Memoona Nasreen', 'email' => 'memoonanasreen69@gmail.com', 'phone' => '3315177734'],
            ['emis' => '297', 'school' => 'IMSB Vi to X sector G-8 1 Ibd', 'name' => 'Muhammad Irfan', 'email' => 'mirfan180172@gmail.com', 'phone' => '3335527648'],
            ['emis' => '300', 'school' => 'IMS (I-V) F8/3', 'name' => 'Asma zahid', 'email' => 'asmazahid599@gmail.com', 'phone' => '331'],
            ['emis' => '301', 'school' => 'IMSB VI,I-X F-8/3', 'name' => 'Dr. Ehsan Mehmood', 'email' => 'drehsanmahmood@gmail.com', 'phone' => '3335300883'],
            ['emis' => '303', 'school' => 'IMSB (VI-X) G-7/3-1, Islamabad', 'name' => 'Bakht Nisar', 'email' => 'kzsmsbg731@gmail.com', 'phone' => '3469157220'],
            ['emis' => '304', 'school' => 'IMCB G-6/ 4', 'name' => 'Muhammad Azam (VP/Admission Incharge)', 'email' => 'azamnuml@gmail.com', 'phone' => '3335418018'],
            ['emis' => '305', 'school' => 'Islamabad Model College for Boys G-6/2, Islamabad', 'name' => 'Dr. Ghulam Dastgeer', 'email' => 'gdastgeer@hotmail.com', 'phone' => '0333-5142787'],
            ['emis' => '306', 'school' => 'IMSB(VI-X) F-6/2', 'name' => 'Raza Hussain', 'email' => 'razahussain74.rh@gmail.com', 'phone' => '0331-5102777'],
            ['emis' => '307', 'school' => 'IMCB G-7/2', 'name' => 'Muhammad Ahsen', 'email' => 'ahsen3542@gmail.com', 'phone' => '3335163490'],
            ['emis' => '308', 'school' => 'IMCB G-7/4', 'name' => 'Mansoor Ahmed Shah', 'email' => 'smashah.education@gmail.com', 'phone' => '3458162302'],
            ['emis' => '315', 'school' => 'Imsb vi-x G-8/4 Islamabad', 'name' => 'Azizullah Soomro', 'email' => 'soomro.mnc@gmail.com', 'phone' => '3009710913'],
            ['emis' => '316', 'school' => 'IMSB TECH (VI_VIII)', 'name' => 'GHAFOOR UR REHMAN', 'email' => 'gkhattak1966@gmail.com', 'phone' => '3345450634'],
            ['emis' => '317', 'school' => 'IMSB (VI-X) E/9,Ibd.', 'name' => 'Naveed Altaf Sheikh', 'email' => 'naveed.sh.66.ns@gmail.com', 'phone' => '3366692926'],

            // Urban-II
            ['emis' => '250', 'school' => 'IMSG (VI-X)G.9/3', 'name' => 'MS.Ruqia Parveen', 'email' => 'ddoimsgid8820@gmail.com', 'phone' => '03335145602'],
            ['emis' => '251', 'school' => 'IMSG (VI-X),G-9/4,Islamabad.', 'name' => 'Ms. Lubna Tasleem', 'email' => 'principalimsg.g94@gmail.com', 'phone' => '03005226560'],
            ['emis' => '252', 'school' => 'IMS(1-V) No 2 G-9/4 lbd', 'name' => 'Naeema firdous', 'email' => 'ddoimsno.2.g.9.4ibd@gmail.com', 'phone' => '03335394415'],
            ['emis' => '253', 'school' => 'IMS (I-V) No1 G 9/ 4 Islamabad', 'name' => 'Rizwana Nawshad', 'email' => 'ddoid8529@gmail.com', 'phone' => '03365402839'],
            ['emis' => '254', 'school' => 'IMS NO 3 G 9/3', 'name' => 'Gull E Syeda', 'email' => 'ddoid8520@gmail.com', 'phone' => '03028549827'],
            ['emis' => '255', 'school' => 'IMS (I-V) No.2, St.7, G-9/3, Islamabad', 'name' => 'Shams Ul Nisa Chandio', 'email' => 'ddo8541imsno2g93@gmail.com', 'phone' => '03336296511'],
            ['emis' => '256', 'school' => 'Ims(1_5) G_9/3 number one', 'name' => 'Riffat sifaat', 'email' => 'ims22education@gmail.com', 'phone' => '03455322070'],
            ['emis' => '257', 'school' => 'IMCG G-9/2', 'name' => 'Parveen Akhter Malik', 'email' => 'imcgg9-2@gmail.com', 'phone' => '03009104440'],
            ['emis' => '258', 'school' => 'IMSG(I-X) G-9/1', 'name' => 'Taskeen begum', 'email' => 'imsgg91@gmail.com', 'phone' => '03321900529'],
            ['emis' => '259', 'school' => 'Islamabad Model School (I-V)#1,G-9/2 Islamabad', 'name' => 'Mrs Sameena Zia', 'email' => 'ddorukhsananasreen@gmail.com', 'phone' => '+92 321 5282738'],
            ['emis' => '260', 'school' => 'IMS I-V no 2 G-9/2', 'name' => 'Qudsia Dilshad', 'email' => 'id8559ddo@gmail.com', 'phone' => '03215080552'],
            ['emis' => '261', 'school' => 'IMS(I-V) NO.03 G-9/2,Islamabad', 'name' => 'Mrs.Zeba Samin Arain', 'email' => 'imsivno3g92@gmail.com', 'phone' => '0321-5103672'],
            ['emis' => '262', 'school' => 'IMS  (  I  -  V  )', 'name' => 'kaneez fatima', 'email' => 'ddoid8527@gmail.com', 'phone' => '03365013027'],
            ['emis' => '263', 'school' => 'Ims(1-5)g9/1', 'name' => 'Asma khan', 'email' => 'ddoimsid8539@gmail.com', 'phone' => '03349472568'],
            ['emis' => '264', 'school' => 'IMS (I-V), F/10-1', 'name' => 'Salma Mehar', 'email' => 'ddoimsid8548@gmail.com', 'phone' => '03365311739'],
            ['emis' => '265', 'school' => 'IMS(I-V) F-10/2', 'name' => 'Ms Humaira Shaheen', 'email' => 'humairashaheen123@gmail.com', 'phone' => '03335279427'],
            ['emis' => '266', 'school' => 'IMS I-V F10/4', 'name' => 'Ms Tahira akram', 'email' => 'ddo8553.ims.f.10.4@gmail.com', 'phone' => '03335507584'],
            ['emis' => '267', 'school' => 'IMSG (vi-x)G-10/1', 'name' => 'Ghazala parveen', 'email' => 'ghazalausman001@gmail.com', 'phone' => '03365382140'],
            ['emis' => '268', 'school' => 'IMSG (I-X) G-10/3', 'name' => 'Nahida Gulzar', 'email' => 'ddoimsgg1038851@gmail.com', 'phone' => '3215668589'],
            ['emis' => '269', 'school' => 'IMS(I-V)G-10/3', 'name' => 'Samra Kalsoom', 'email' => 'samranom@yahoo.com', 'phone' => '03015657997'],
            ['emis' => '270', 'school' => 'IMS(I-V), G-10/4', 'name' => 'Dr. Farhat Parveen', 'email' => 'ddo8547imsivg104@gmail.com', 'phone' => '03215026015'],
            ['emis' => '271', 'school' => 'IMS(I-V) G-10/1 Islamabad', 'name' => 'Aliya Tabassam', 'email' => 'aliya.tabassam.bhatti@gmail.com', 'phone' => '03055549561'],
            ['emis' => '272', 'school' => 'IMS(I-V) #1, G-10/2', 'name' => 'Lubna Rafiq', 'email' => 'imsno1g102@gmail.com', 'phone' => '03035009006'],
            ['emis' => '273', 'school' => 'IMS( I- V) NO 2 G10/2', 'name' => 'Saima Farheen', 'email' => 'imsno2g102@gmail.com', 'phone' => '03048737043'],
            ['emis' => '274', 'school' => 'IMS (I-V)G-11/1, Islamabad.', 'name' => 'Ms.Taranum Altaf Usmani', 'email' => 'ims125g11@gmail.com', 'phone' => '03345607363'],
            ['emis' => '275', 'school' => 'IMSG(I-X)G-11/2', 'name' => 'Ms Zubaida', 'email' => 'isbmodelschoolg112@gmail.com', 'phone' => '+92 347 8210003'],
            ['emis' => '276', 'school' => 'IMSG VI -X F11/1', 'name' => 'Ms .Zaib un nisa', 'email' => 'ddo8857@gmail.com', 'phone' => '0331-3331563'],
            ['emis' => '277', 'school' => 'IMS (I-V) G-11/2', 'name' => 'Rubina Chanzaib', 'email' => 'imsg11.277@gmail.com', 'phone' => '3303710808'],
            ['emis' => '278', 'school' => 'IMCG G-11/1', 'name' => 'Raheela Awais', 'email' => 'modelschoolg11@gmail.com', 'phone' => '+923335189229'],
            ['emis' => '279', 'school' => 'IMSG VI-X I-8 1', 'name' => 'Zahra Bukhari', 'email' => 'zbukhari74@gmail.com', 'phone' => '03359567951'],
            ['emis' => '280', 'school' => 'IMS(I-V)I-8/1 Islamabad', 'name' => 'Shafia Bibi', 'email' => 'ddo8542ims@gmail.com', 'phone' => '03365167702'],
            ['emis' => '281', 'school' => 'IMSG (I-V111) I-9/4', 'name' => 'Samina Shaikh', 'email' => 'saminashaikh19699@gmail.com', 'phone' => '03355422575'],
            ['emis' => '282', 'school' => 'IMS (1_V) No 1 I-9/4', 'name' => 'Farmina Qadir', 'email' => 'ddoid8532@gmail.com', 'phone' => '03315632027'],
            ['emis' => '283', 'school' => 'IMS I-V No 2 I-9/4', 'name' => 'Dr. Noor E Ain', 'email' => 'nooreainain@gmail.com', 'phone' => '03005733879'],
            ['emis' => '284', 'school' => 'IMSG I-VIII I-8/1, Islamabad', 'name' => 'Zahida Akhtar', 'email' => 'zahidaakhtar4@gmail.com', 'phone' => '03365644417'],
            ['emis' => '285', 'school' => 'IMS (I-V) AIOU Colony', 'name' => 'Khair ul Wara', 'email' => 'ddo8551h8@gmail.com', 'phone' => '3318689225'],
            ['emis' => '286', 'school' => 'IMCG,I-9/1, Islamabad', 'name' => 'Mrs. Ghazala Bashir Khan', 'email' => 'imcgi91islamabad@gmail.com', 'phone' => '+923335134154'],
            ['emis' => '287', 'school' => 'IMSG VI-X I-10/4', 'name' => 'Gul-e-Rana', 'email' => 'ddoimsg8822@gmail.com', 'phone' => '03125 168 527'],
            ['emis' => '288', 'school' => 'IMSG I-VIII I 10/4', 'name' => 'Nighat Mehnaz khattak', 'email' => 'ddoimsg8716@gmail.com', 'phone' => '0335 5886054'],
            ['emis' => '289', 'school' => 'IMS(I-V) I-10/1 no1', 'name' => 'Rehana Yasmin', 'email' => 'ddoims8502@gmail.com', 'phone' => '03325028297'],
            ['emis' => '290', 'school' => 'IMS (1-5) no 2 I -10/1', 'name' => 'Mrs Naveeda Abu Bakar', 'email' => 'schoolims117@gmil.com', 'phone' => '03348083840'],
            ['emis' => '291', 'school' => 'IMS (I-V) I-10/2', 'name' => 'Amna Khan', 'email' => 'ddoims8545@gmail.com', 'phone' => '03455142296'],
            ['emis' => '292', 'school' => 'IMS( I-V) No:2, I-9/1', 'name' => 'Javeria Aslam', 'email' => 'aslamjaveria123@gmail.com', 'phone' => '0334 5456194'],
            ['emis' => '293', 'school' => 'IMSG VI-X l-9/4', 'name' => 'Munazza Jabeen', 'email' => 'munazzajabeen18@gmail.com', 'phone' => '03455135271'],
            ['emis' => '294', 'school' => 'IMS(I-V)No.1,I-9/1,Ibd', 'name' => 'Mehreen Imtiaz', 'email' => 'i91no1ims@gmail.com', 'phone' => '03445512416'],
            ['emis' => '296', 'school' => 'IMCB G9/4', 'name' => 'Abdul Waheed', 'email' => 'imcbg9.4@gmail.com', 'phone' => '03335145497'],
            ['emis' => '298', 'school' => 'IMSB (VI-X) G-10/3', 'name' => 'Dr Maqsood Ahmed', 'email' => 'maqsood517@yahoo.com', 'phone' => '03335848020'],
            ['emis' => '299', 'school' => 'IMSB G-9/1 Islamabad', 'name' => 'Inam Jahangir', 'email' => 'inam_jahangir@yahoo', 'phone' => '03334543629'],
            ['emis' => '302', 'school' => 'IMSB (VI-X) G-11/2 Ibd', 'name' => 'Dr Khurshid Alam', 'email' => 'imsbg11two@gmail.com', 'phone' => '3369168383'],
            ['emis' => '309', 'school' => 'IMSB (VI-X) NO.1, I-9/4, ISLAMABAD', 'name' => 'DR.GHULAM SARWAR', 'email' => 'sarwar369@gmail.com', 'phone' => '03335150831'],
            ['emis' => '310', 'school' => 'IMCB I 10/1 St 17', 'name' => 'Muhammad Akram', 'email' => 'imcbiten@gmail.com', 'phone' => '+92 300 5548025'],
            ['emis' => '311', 'school' => 'IMSB VI-X NO 02 I-9/4', 'name' => 'Muhammad ZUBAIR', 'email' => 'imsb311@gmail.com', 'phone' => '03335250668'],
            ['emis' => '312', 'school' => 'IMSB i-10/2', 'name' => 'Azizwahid', 'email' => 'aziz.wahid2014@gmail.com', 'phone' => '03028182062'],
            ['emis' => '313', 'school' => 'IMSB (I-X)I-8/1 Islamabad', 'name' => 'Muhammad Imran', 'email' => 'ddo.imsbi81@gmail.com', 'phone' => '03360951498'],
            ['emis' => '314', 'school' => 'IMSB (VI-X) I-8/4,IBD', 'name' => 'Muhammad Ejaz Alam', 'email' => 'imsb8855@gmail.com', 'phone' => '0344-0628144'],

            // Bhara Kau
            ['emis' => '401', 'school' => 'Adnan Arshad Shaheed Model College, (VI-XII), (BSK)  Bhara Kau', 'name' => 'Mr. Fida Ur Rehman', 'email' => 'fidaurrehman2@gmail.com', 'phone' => '3318856955'],
            ['emis' => '402', 'school' => 'Farhad Ahmed Shaheed Model college for Boys (VI-XII), Chak Shahzad', 'name' => 'Mr. Feroz Khan', 'email' => 'ahsen3542@gmail.com', 'phone' => '3335281376'],
            ['emis' => '407', 'school' => 'Zeeshan Shaheed Model College for Boys (VI-XII),  Pind Begwal', 'name' => 'Dr. Saeed Anwar', 'email' => 'drsaeedanwarmalik@gmail.com', 'phone' => '3328940371'],
            ['emis' => '403', 'school' => 'Sohail Aslam Shaheed Model School for Boys (I-X) Bhara Kau', 'name' => 'Mr. Allah Dad Malik', 'email' => 'allahdad.malik4@gmail.com', 'phone' => '3455223578'],
            ['emis' => '404', 'school' => 'Adil Shahzad Shaheed Model School for Boys (I-X)  Chattar', 'name' => 'Mr. Muhammad Tahir Abbasi', 'email' => 'tahirabbasivp@gmail.com', 'phone' => '3351152692'],
            ['emis' => '405', 'school' => 'Zeeshan Ali Shaheed Model School for Boys (VI-X), Kuri', 'name' => 'Mr. Rehman Buksh', 'email' => 'rehmanbux1976@gmail.com', 'phone' => '3023634970'],
            ['emis' => '406', 'school' => 'Rizwan Sarir Shaheed Model School for Boys (VI-X)  Noor Pur Shahan', 'name' => 'Mr. Muhammad Anwar', 'email' => 'anwar1801@gmail.com', 'phone' => '3335252695'],
            ['emis' => '408', 'school' => 'Tahir Shaheed Model School for Boys (I-X) Shadara', 'name' => 'Dr. Zia Ur Rehman', 'email' => 'hm3639253@gmail.com', 'phone' => '3005356608'],
            ['emis' => '409', 'school' => 'Waseem Iqbal Shaheed Model School for Boys (VI-X)  Rawal Dam', 'name' => 'Dr. Sham Kumar', 'email' => 'khurshidalam90064@gmail.com', 'phone' => '0332-2766133'],
            ['emis' => '410', 'school' => 'Daud Shaheed Model School for Boys (VI-X)  Talhar', 'name' => 'Mr Taj Ali Khan', 'email' => 'tajwazir76@gmail.com', 'phone' => '0334-5387591'],
            ['emis' => '411', 'school' => 'Haris Shaheed Model School for Boys (I-X)  Saidpur', 'name' => 'Mr. Khalid Hussain Channa', 'email' => 'khchanna@gmail.com', 'phone' => '0333-5160722'],
            ['emis' => '414', 'school' => 'Atif Ur Rehman Shaheed Model School for Boys (I-X) Maira Begwal', 'name' => 'Mr. Ijaz Ahmed', 'email' => 'ijaza024@gmail.com', 'phone' => '3145375579'],
            ['emis' => '416', 'school' => 'Shahzad Ijaz Shaheed Model School for Boys (I-X) Phulgran', 'name' => 'Mr. MUHAMMAD LATIF', 'email' => 'curious990@gmail.com', 'phone' => '3215852384'],
            ['emis' => '412', 'school' => 'Zia Ul Islam Shaheed Model School for Boys (I-VIII)  Bobri', 'name' => 'Mr. Naseer Ahmed', 'email' => 'naseertgt101@gmail.com', 'phone' => '3345484692'],
            ['emis' => '413', 'school' => 'Hamid Ali Khan Shaheed Model School for Boys (I-VIII) Jandala', 'name' => 'Mr. Zahoor Elahi', 'email' => 'abdulfattahsolangi@gmail.com', 'phone' => '0311-5541088'],
            ['emis' => '439', 'school' => 'Basit Ali Sardar Shaheed Model School for Boys (I-VIII) Malpur', 'name' => 'Mr. Hakim Khan', 'email' => 'hakimkhaneducater@gmail.com', 'phone' => '0300-5542415'],
            ['emis' => '415', 'school' => 'Azhar Naseer Shaheed Model School for Boys (I-VIII) Mohra Noor, NIH', 'name' => 'Mr. Imdad Ali', 'email' => 'shafqat.hussain8120@gmail.com', 'phone' => '0332-2390680'],
            ['emis' => '417', 'school' => 'Yasir Iqbal Shaheed Model School for Boys (I-VIII), Kot Hathial, NA', 'name' => 'Mr. Shafi uz Zaman', 'email' => 'ddoimsb.kothathial8729@gmail.com', 'phone' => '0300-5594380'],
            ['emis' => '418', 'school' => 'Ali Rehman Shaheed Model School for Boys (I-VIII) Malwar', 'name' => 'Tabarak Hussain Shah', 'email' => 'arif.khokhhar68@gmail.com', 'phone' => '3025442566'],
            ['emis' => '419', 'school' => 'Mujahid Hussain Shaheed Model School for Boys (I-VIII) Satra Meel', 'name' => 'Mr. Khadim Hussain', 'email' => 'mashorikhadim68@gmail.com', 'phone' => '3350444255'],
            ['emis' => '441', 'school' => 'Shayan Nasir Shaheed Model School for Boys (I-VIII) Chatta Bukhtawar', 'name' => 'Mr. Arshad Ali', 'email' => 'arshedali1972@gmail.com', 'phone' => '3456864144'],
            ['emis' => '420', 'school' => 'IMSB (I-V) Athal', 'name' => 'Mr. Muhammad Kabir', 'email' => 'muhammadkabir1967@gmail.com', 'phone' => '3155152302'],
            ['emis' => '421', 'school' => 'IMSB (I-V) Bhuddo', 'name' => 'Mr.Muhammad Moin', 'email' => 'gulwazir65@gmail.com', 'phone' => '3418774212'],
            ['emis' => '423', 'school' => 'Shafaqat Shaheed Model School for Boys (I-V) Dhoke Jerrani', 'name' => 'Dr Arif Masih', 'email' => 'noorahmaedhaji@gmai.com', 'phone' => '3455104774'],
            ['emis' => '424', 'school' => 'IMSB (I-V) Dhoke Syedan', 'name' => 'Mr. Gulfraz Ahmed', 'email' => 'gulfrazreal@gmail.com', 'phone' => '3475080308'],
            ['emis' => '425', 'school' => 'IMSB (I-V) Dohalla Syedan', 'name' => 'Mr. Nasir Zafar', 'email' => 'nasirzfr@gmail.com', 'phone' => '0333-5262972'],
            ['emis' => '426', 'school' => 'IMSB (I-V) Kalran', 'name' => 'Mr. Muneer Ahmed', 'email' => 'muneerbajwa@gmail.com', 'phone' => '3337051870'],
            ['emis' => '427', 'school' => 'Farhan Jalal Shaheed Model School for Boys (I-V) Malot', 'name' => 'Mr. Muhammad Amjid', 'email' => 'kashifpayslip@gmail.com', 'phone' => '0346-5465144'],
            ['emis' => '428', 'school' => 'IMSB (I-V) Mangial', 'name' => 'Mr. Sarfaraz Mehmood', 'email' => 'sarfrazmehmood68@gmail.com', 'phone' => '3335159638'],
            ['emis' => '429', 'school' => 'IMSB (I-V) Mall', 'name' => 'Mr. Atifa Ahsan', 'email' => 'atifaahsan80@gmail.com', 'phone' => '3234385203'],
            ['emis' => '430', 'school' => 'Imran Ali Shaheed Model School for Boys (I-V) Noor Pur Shahan', 'name' => 'Mr. Muhammad Anwar Saeed', 'email' => 'walikhan1964@gmail.com', 'phone' => '3335251587'],
            ['emis' => '431', 'school' => 'IMSB (I-V) Palali', 'name' => 'Mr. Muhammad Nawaz', 'email' => 'mnsmore67@gmail.com', 'phone' => '3045151904'],
            ['emis' => '432', 'school' => 'Bilal Arshad Shaheed Model School for Boys (I-V) Pind Begwal', 'name' => 'Dr. Saeed Anwar', 'email' => 'drsaeedanwarmalik@gmail.com', 'phone' => '3328940371'],
            ['emis' => '433', 'school' => 'IMSB (I-V) Rumli', 'name' => 'Mr. Muhammad Hussain', 'email' => 'mashahidibd@gmail.com', 'phone' => '333 5409825'],
            ['emis' => '434', 'school' => 'IMSB (I-V) Sihali', 'name' => 'Mr. Javed Mehar', 'email' => 'rajamzahid81@gmail.com', 'phone' => '3006009567'],
            ['emis' => '435', 'school' => 'Umer Hayat Shaheed Model School for Boys (I-V) Talhar', 'name' => 'Mr Taj Ali Khan', 'email' => 'mazharpayslip0@gmail.com', 'phone' => '0334-5387591'],
            ['emis' => '436', 'school' => 'Muhammad Waqar Shaheed Model School for Boys (I-V) Kot Hathial (QA)', 'name' => 'Muhammad Iftikhar', 'email' => 'ranasattar065@gmail.com', 'phone' => '3367714504'],
            ['emis' => '437', 'school' => 'IMSB (I-V) Gokina', 'name' => 'Mr. Mahmood Abbasi', 'email' => 'nasirkhanniazy@gmail.com', 'phone' => '3329200124'],
            ['emis' => '438', 'school' => 'Sohail Sardar Shaheed Model School for Boys (I-V) Kuri', 'name' => 'Mr. Zulfiqar Ali', 'email' => 'abdulwaheed1april@gmail.com', 'phone' => '3345411629'],
            ['emis' => '440', 'school' => 'Hamid Saif Shaheed Model School for Boys (I-V) Rawal Dam', 'name' => 'Mr. Ch. Sajid Mehmood', 'email' => 'rashidkiani15@gmail.com', 'phone' => '3335134932'],
            ['emis' => '442', 'school' => 'IMCG Margalla Town', 'name' => 'Ms. Shumaila Ghazal', 'email' => 'shamailatauqeer12@gmail.com', 'phone' => '3335449808'],
            ['emis' => '443', 'school' => 'IMCG Kot Hathial', 'name' => 'Ms. Tahira Nasreen', 'email' => 'tahiranasreen04@gmail.com', 'phone' => '3005301740'],
            ['emis' => '444', 'school' => 'IMCG University Colony', 'name' => 'Ms Asma Noureen', 'email' => 'mrs.shagufta.jamil@gmail.com', 'phone' => '3335378022'],
            ['emis' => '446', 'school' => 'IMCG NHC', 'name' => 'Ms. Saiqa Arif', 'email' => 'saiqa4810@gmail.com', 'phone' => '3315681200'],
            ['emis' => '449', 'school' => 'IMCG Mal Pur', 'name' => 'Ms. Munazza Yasmin Anwar', 'email' => 'munazza.yasmin1969@gmail.com', 'phone' => '3365292056'],
            ['emis' => '453', 'school' => 'IMCG Maira Begwal', 'name' => 'Ms,Asma Intaisar Ahmed', 'email' => 'ddoimcgmairabegwalibd@gmail.com', 'phone' => '0336-3028158'],
            ['emis' => '455', 'school' => 'IMCG Pind Begwal', 'name' => 'Ms. Sajida Perveen', 'email' => 'gulezehra87@gmail.com', 'phone' => '3325842050'],
            ['emis' => '451', 'school' => 'IMCG (I-XII) Rawal Town', 'name' => 'Ms. Rizwana Qadir', 'email' => 'farzanasyed001@gmail.com', 'phone' => '3015630571'],
            ['emis' => '447', 'school' => 'IMSG (I-X) Gokina', 'name' => 'Ms. Saman Attia Hassan', 'email' => 'samanatiya@gmail.com', 'phone' => '3335318186'],
            ['emis' => '448', 'school' => 'IMSG (I-X) Kuri', 'name' => 'Ms. Amna Bibi', 'email' => 'amnabibi1969@gmail.com', 'phone' => '3315153914'],
            ['emis' => '445', 'school' => 'IMSG (I-X) NHC', 'name' => 'Ms. Aneela Naseer,', 'email' => 'aneelanaseer7a@gmail.com', 'phone' => '3215124651'],
            ['emis' => '450', 'school' => 'IMSG (I-X) Phulgran', 'name' => 'Ms. Huma Rana Saifi', 'email' => 'humaranasaifi@gmail.com', 'phone' => '3363342883'],
            ['emis' => '452', 'school' => 'IMSG (I-X) Talhar', 'name' => 'Ms. Asma Farman', 'email' => 'asmafarman80@gmail.com', 'phone' => '3335304013'],
            ['emis' => '454', 'school' => 'IMSG (I-X) Lakhwal', 'name' => 'Ms. Nighat Jabeen', 'email' => 'nighatjabeenkhan@gmail.com', 'phone' => '3337567716'],
            ['emis' => '456', 'school' => 'IMSG (I-X) Noor Pur Shahan', 'name' => 'Ms. Aneela Asif', 'email' => 'aliazareen123@gmail.com', 'phone' => '3345073773'],
            ['emis' => '457', 'school' => 'IMSG (I-X) Shahdra Khurd', 'name' => 'Ms. Uzma Batool', 'email' => 'irfana.edu@gmail.com', 'phone' => '3365030613'],
            ['emis' => '458', 'school' => 'IMSG (I-X) Said Pur', 'name' => 'Ms. Shaista Abbasi', 'email' => 'shaistaabbasi76@gmail.com', 'phone' => '3445173403'],
            ['emis' => '459', 'school' => 'IMSG (I-X) Malot', 'name' => 'Ms. Afshan Zaki', 'email' => 'afshanzaki15@gmail.com', 'phone' => '3345021948'],
            ['emis' => '463', 'school' => 'IMSG (I-X) Mohra Noor', 'name' => 'Ms. Ruth Salamat', 'email' => 'eshban.ruth1@gmail.com', 'phone' => '3330513687'],
            ['emis' => '460', 'school' => 'IMSG (I-VIII) Shahdra Kalan', 'name' => 'Ms. Rehana Noor', 'email' => 'tahiralilla@gmail.com', 'phone' => '3335729212'],
            ['emis' => '461', 'school' => 'IMSG (I-VIII) Bain Nala', 'name' => 'Ms. Samia Noor', 'email' => 'noor.saym@gmail.com', 'phone' => '3315016445'],
            ['emis' => '462', 'school' => 'IMSG (I-VIII) Mandla', 'name' => 'Ms. Farah Naz', 'email' => 'sajidaparveen410@gmail.com', 'phone' => '3355593917'],
            ['emis' => '464', 'school' => 'IMSG (I-VIII) Bhara Kau', 'name' => 'Ms. Bilqees InhamUl Haq', 'email' => 'bilqeesinam@gmail.com', 'phone' => '3022881062'],
            ['emis' => '465', 'school' => 'IMSG (I-VIII) Bobri', 'name' => 'Ms Azeema Bibi', 'email' => 'farhatjafar91@gmail.com', 'phone' => '0345-5279927'],
            ['emis' => '466', 'school' => 'IMSG (I-VIII) Kot Hathial', 'name' => 'Ms. Fozia Shaoib', 'email' => 'attiyaperveen1968@gmail.com', 'phone' => '3315127582'],
            ['emis' => '467', 'school' => 'IMSG (I-VIII) Sanjalian', 'name' => 'Ms. Jamila Hadi', 'email' => 'imsgsanjalian@gmail.com', 'phone' => '3471531755'],
            ['emis' => '472', 'school' => 'IMSG (I-VIII) Mohrian', 'name' => 'Ms. Imtiaz Begum', 'email' => 'imtiazbegum70@gmail.com', 'phone' => '3455395377'],
            ['emis' => '468', 'school' => 'IMSG (I-V) Athal', 'name' => 'Ms. Adeela Nawaz Cheema', 'email' => 'adeelanawaz27@gmail.com', 'phone' => '3310487014'],
            ['emis' => '469', 'school' => 'IMSG (I-V) Chak Shahzad', 'name' => 'Ms. Afshan Malik', 'email' => 'afshanmalik43@gmail.com', 'phone' => '3009197910'],
            ['emis' => '470', 'school' => 'IMSG (I-V) Dhoke Jerrani', 'name' => 'Ms. Gul Naz', 'email' => 'asyia.shafiq@gmail.com', 'phone' => '0335-1625636'],
            ['emis' => '471', 'school' => 'IMSG (I-V) Kot Hathial (NA)', 'name' => 'Ms. Irfana Usman', 'email' => 'imsg.kh.na@gmail.com', 'phone' => '3351186777'],
            ['emis' => '473', 'school' => 'IMSG (I-V) Pind Begwal (Dana)', 'name' => 'Ms. Romana Bashir', 'email' => 'shahnazakhtar8864@gmail.com', 'phone' => '3455461977'],
            ['emis' => '474', 'school' => 'IMSG (I-V) Shah Pur', 'name' => 'Ms. Tabasum Shaheen', 'email' => 'tabbasum.shaheen98@gmail.com', 'phone' => '3009729311'],
            ['emis' => '475', 'school' => 'IMSG (I-V) Subban', 'name' => 'Ms. Riffat Sultana', 'email' => 'surriya03@gmail.com', 'phone' => '3349560469'],
            ['emis' => '476', 'school' => 'IMSG (I-V) Shahzad Town', 'name' => 'Ms. Naheeda Shahms', 'email' => 'naheedashams1987@gmail.com', 'phone' => '3365541361'],
            ['emis' => '477', 'school' => 'IMSG (I-V) Bhara Kau (NA)', 'name' => 'Ms. Nosheen', 'email' => 'uwhk.ty@gmail.com', 'phone' => '3212772554'],
            ['emis' => '478', 'school' => 'IMSG (I-V) Mal Pur', 'name' => 'Ms. Munazza Yasmin Anwar', 'email' => 'munazza.yasmin1969@gmail.com', 'phone' => '3665292056'],
            ['emis' => '479', 'school' => 'IMSG (I-V) Maira Mal Pur', 'name' => 'Ms. Raisa Fatima', 'email' => 'ddosanjalian@gmail.com', 'phone' => '3015244430'],

            // Sihala
            ['emis' => '501', 'school' => 'IMCG Herdogher Islamabad', 'name' => 'MRS FARZANA SANA', 'email' => 'farzanaafzal1972@gmail.com', 'phone' => '0332-5870787'],
            ['emis' => '502', 'school' => 'IMCG Rawat', 'name' => 'ROBBINA SHAHEEN', 'email' => 'shaheenr6@gmail.com', 'phone' => '0306-4306369'],
            ['emis' => '503', 'school' => 'IMCG HUMAK', 'name' => 'ASIFA HANIF', 'email' => 'asifahanif786@gmail.com', 'phone' => '3215428820'],
            ['emis' => '504', 'school' => 'IMSG(VI-X)Sihala', 'name' => 'IFFAT PARVEEN GILLANI', 'email' => 'igillaniqau@gmail.com', 'phone' => '0300-52772767'],
            ['emis' => '505', 'school' => 'IMSG(I-X)Nara Syedan', 'name' => 'NABILA NAWAZ', 'email' => 'nabeelanawaz76@gmail.com', 'phone' => '0300-9820898'],
            ['emis' => '506', 'school' => 'IMCG, Dhoke Gangal', 'name' => 'DR. FOUZIA YOUNUS', 'email' => 'fouziyounus@gmail.com', 'phone' => '0321-8600871'],
            ['emis' => '507', 'school' => 'IMCG (I-X) Pind Malkan', 'name' => 'NUSRAT SULTANA', 'email' => 'wnusrat9@gamil.com', 'phone' => '3435784904'],
            ['emis' => '508', 'school' => 'IMCG Lohi Bher', 'name' => 'MEHR-UN-NISA', 'email' => 'mehrunnisa222@gmail.com', 'phone' => '0334-5344290'],
            ['emis' => '509', 'school' => 'IMCG Mohra Nagial', 'name' => 'BUSHRA HADYATULLAH', 'email' => 'bushrahadyatullah@gmail.com', 'phone' => '0307-4456006'],
            ['emis' => '509', 'school' => 'IMCG Mohra Nagial (Evenimg)', 'name' => 'RIZWANA RAFIQ', 'email' => 'rizwanarafiq442@gmail.com', 'phone' => '0323-5588771'],
            ['emis' => '510', 'school' => 'IMSG (I-X) HUMAK', 'name' => 'HALEEMA KHATOON', 'email' => 'haleema17101968@gmail.com', 'phone' => '0307-8130040'],
            ['emis' => '511', 'school' => 'IMSG (I-X) GAGRI', 'name' => 'ANJUM SAQLAIN KAYANI', 'email' => 'anjumsaqlainkayani@gmail.com', 'phone' => '0337-9823884'],
            ['emis' => '512', 'school' => 'IMSG(I-X)Upran Gurha', 'name' => 'KOUKAB HUMA', 'email' => 'koukabhuma@gmail.com', 'phone' => '0333-9389628'],
            ['emis' => '513', 'school' => 'IMSG (I-VIII) Bhimber Tarar', 'name' => 'TAMKEEN NAVEED', 'email' => 'tamkeennaveed@gmail.com', 'phone' => '3315507645'],
            ['emis' => '514', 'school' => 'IMSG(I-VIII)Mohri Rawat', 'name' => 'SADAF JAVED', 'email' => 'sadafjaved1980@gmail.com', 'phone' => '0334-5458101'],
            ['emis' => '515', 'school' => 'IMSG (I-X) R/C Rawat', 'name' => 'MADEEHA', 'email' => 'madeeha_2006pk@hotmail.com', 'phone' => '0331-4181308'],
            ['emis' => '516', 'school' => 'IMSG (I-VIII) Bhangril Khurd', 'name' => 'NISMA ZAHRA', 'email' => 'nismazahra506@gmail.com', 'phone' => '0335-6641562'],
            ['emis' => '517', 'school' => 'IMSG (I-VIII) Rajwal', 'name' => 'SARWAT AZIZ', 'email' => 'sarwataziz69@gmail.com', 'phone' => '0333-5278046'],
            ['emis' => '518', 'school' => 'IMSG (I-X) Dhaliala', 'name' => 'RIFFAT IJAZ', 'email' => 'riffatijaz05@gmail.com', 'phone' => '0336-5010150'],
            ['emis' => '519', 'school' => 'IMSG ( I-X) Niazian', 'name' => 'GHAZALA UMER', 'email' => 'ghazalagangaal@gmail.com', 'phone' => '0325-5001248'],
            ['emis' => '520', 'school' => 'IMSG(I-V) HUMAK (M.T)', 'name' => 'AMNA JAVED', 'email' => 'amnaanser1@gmail.com', 'phone' => '0333-5345519'],
            ['emis' => '521', 'school' => 'IMSG (I-VIII) PEIJA (FA) ISB', 'name' => 'KANIZ AKHTAR', 'email' => 'kanizakhter75@gmail.com', 'phone' => '0345-5250167'],
            ['emis' => '522', 'school' => 'IMSG (I-VIII) PINDORI SYEDAN', 'name' => 'RUKHSANA SHAREF', 'email' => 'rukhsanasharif456@gmail.com', 'phone' => '0332-5425011'],
            ['emis' => '523', 'school' => 'IMSG (I-VIII) Miana Thub', 'name' => 'FUQRAZ BEGUM', 'email' => 'fuqrazbegum99@gmail.com', 'phone' => '0301-5044003'],
            ['emis' => '524', 'school' => 'IMSG(I-VIII) JANDALA', 'name' => 'NEELAM ZAHOOR', 'email' => 'zahoorneelam@gmail.com', 'phone' => '0300-5396639'],
            ['emis' => '525', 'school' => 'IMSG (I-V) Rawat', 'name' => 'ALIYA TABASSUM', 'email' => 'aliyachaudhry9@gmail.com', 'phone' => '0341-8952685'],
            ['emis' => '526', 'school' => 'IMSG (I-V) Sheikhpur Rawat', 'name' => 'NASREEN AKHTAR', 'email' => 'nasreen121472@gmail.com', 'phone' => '0313-5248305'],
            ['emis' => '527', 'school' => 'IMSG (I-V) Herdogher', 'name' => 'FAZINAT JAN', 'email' => 'fazinatjan@gmail.com', 'phone' => '0344-1548095'],
            ['emis' => '528', 'school' => 'IMSG (I-V)  Mughal', 'name' => 'IRAM ZAMEER KAYANI', 'email' => 'iramzameer59@gmail.com', 'phone' => '0343-517858'],
            ['emis' => '529', 'school' => 'IMSG (I-V) SIHALA', 'name' => 'MUBASHARA NASEEM', 'email' => 'mubasharanaseem222@gmail.com', 'phone' => '3345273534'],
            ['emis' => '530', 'school' => 'IMSG (I-V) SIHALA MIRZIAN', 'name' => 'SABIHA KHANUM', 'email' => 'sabihakhanum238@gmail.com', 'phone' => '0333-5265249'],
            ['emis' => '531', 'school' => 'IMSG (I-V) Hoon Dhamial', 'name' => 'SEHRISH RASHID', 'email' => 'sehrishrizwan716@gmail.com', 'phone' => '0333-1578277'],
            ['emis' => '532', 'school' => 'IMSG (I-V) GOHRA MAST', 'name' => 'SAMINA SHAHEEN', 'email' => 'saminasgangal@gmail.com', 'phone' => '0371-0994716'],
            ['emis' => '533', 'school' => 'IMSG (I-V) LADHIOT', 'name' => 'FARHAT KALSUM', 'email' => 'farhatkalsum@gmail.com', 'phone' => '0334-8147332'],
            ['emis' => '534', 'school' => 'IMSG (I-V) Humak', 'name' => 'SHAHIDA ABBAS NAQVI', 'email' => 'shahidaabbasnaqvi@gmail.com', 'phone' => '0346-5294455'],
            ['emis' => '536', 'school' => 'IMSG (I-V) Boora Bangial', 'name' => 'SMANA BANARAS', 'email' => 'samanabanaras@gmail.com', 'phone' => '0331-5690314'],
            ['emis' => '537', 'school' => 'IMSG (I-V) Mohri Mughal', 'name' => 'NOREEN ANJAM', 'email' => 'knoreen041@gmail.com', 'phone' => '0304-9904288'],
            ['emis' => '538', 'school' => 'IMSG(I-VIII)PTC SIHALA', 'name' => 'MUNAZZA AFTAB', 'email' => 'munazzaaftab9@gmail.com', 'phone' => '0334-5309678'],
            ['emis' => '539', 'school' => 'IMSG (I-V) PWD', 'name' => 'RUKHSANA KALSOOM', 'email' => 'rukhsanakalsoom@outlook.com', 'phone' => '0343-5075974'],
            ['emis' => '540', 'school' => 'IMSG (I-V) Sihala Khurd', 'name' => 'SAGHIRA ANJUM', 'email' => 'saghiraanjum182@gmail.com', 'phone' => '0334-5415213'],
            ['emis' => '541', 'school' => 'IMCB Mughal', 'name' => 'MUHAMMAD ADNAN', 'email' => 'adnankhi1972@gmail.com', 'phone' => '0335-3932640'],
            ['emis' => '542', 'school' => 'IMSB (VI-X) SIHALA', 'name' => 'YOUSAF HAYAT', 'email' => 'yousafkhattak@gmail.com', 'phone' => '0346-5392584'],
            ['emis' => '543', 'school' => 'IMCB Rawat', 'name' => 'MR. FAIZ SULTAN', 'email' => 'faizsultanphdnuml@gamil.com', 'phone' => '0333-5905246'],
            ['emis' => '544', 'school' => 'IMCB Bhimber Trar', 'name' => 'Iftikhar Hussain', 'email' => 'ifikhar.imcbpind@gmail.com', 'phone' => '0346-5741927'],
            ['emis' => '545', 'school' => 'IMCB HUMAK', 'name' => 'AZIZ-UR-REHAMN', 'email' => 'azizfaisl@gmail.com', 'phone' => '0333-5190514'],
            ['emis' => '546', 'school' => 'IMCB Pahg Panwal', 'name' => 'JUNAID AHMED', 'email' => 'juniad75@gmail.com', 'phone' => '0334-5877547'],
            ['emis' => '547', 'school' => 'IMCB Mohra Nagial', 'name' => 'SYED HASSAN RAZA', 'email' => 'hassanrazazaidi71@gmail.com', 'phone' => '0333-2626529'],
            ['emis' => '548', 'school' => 'IMSB I-X Gagri', 'name' => 'INTIKHAB HUSSAIN', 'email' => 'intikhabhussain1@gmail.com', 'phone' => '0333-5529125'],
            ['emis' => '549', 'school' => 'IMSB (I-X) Dhaliala', 'name' => 'NASIR MASIH', 'email' => 'nasirmsah38@gmail.com', 'phone' => '0333-5513997'],
            ['emis' => '550', 'school' => 'IMSB (I-X), Banni Saran', 'name' => 'ANWAR RAZA', 'email' => 'anwarrazafde@gmail.com', 'phone' => '0300-6044992'],
            ['emis' => '551', 'school' => 'IMSB (I-V) SIHALA', 'name' => 'MUHAMMAD JAMAL', 'email' => '779jamal@gmail.com', 'phone' => '0333-8576779'],
            ['emis' => '552', 'school' => 'IMSB (I-V) Lohi Bher', 'name' => 'AMJAD FAROOQ', 'email' => 'farooqamjad116@gmail.com', 'phone' => '0303-5463649'],
            ['emis' => '553', 'school' => 'IMSB (I-V) BHIMBER TRAR', 'name' => 'SANA ULLAH', 'email' => 'sanaullah090377@gmail.com', 'phone' => '0333-7912720'],
            ['emis' => '554', 'school' => 'IMSB (I-VIII) Ara Burji', 'name' => 'QAISAR ABBAS KHAN', 'email' => 'qaiser23267@gmail.com', 'phone' => '0333-5527951'],
            ['emis' => '555', 'school' => 'IMSB(I-V) HUMAK', 'name' => 'GHULAM HASSAN', 'email' => 'hassanghulam379@gmail.com', 'phone' => '0334-3334464'],
            ['emis' => '556', 'school' => 'IMSB(I-VIII) SIHALA MIRZIAN', 'name' => 'GHULAM SARWAR JARAH', 'email' => 'ghulamsarwar344@gmail.com', 'phone' => '0344-5838836'],
            ['emis' => '557', 'school' => 'IMSB(I-V) Mughal', 'name' => 'NAVEED AHMED', 'email' => 'naveedahmedsatti22@gmail.com', 'phone' => '0331-5545807'],
            ['emis' => '558', 'school' => 'IMSB(I-VIII) HERDOGHER', 'name' => 'MUHAMMAD TAHIR QAMRANI', 'email' => 'tahirqamranifde@gmail.com', 'phone' => '0331-5070992'],
            ['emis' => '559', 'school' => 'IMSB (I-V) Darwala', 'name' => 'MUHAMMAD ASLAM', 'email' => 'juttaslam849@gmail.com', 'phone' => '0346-5103004'],
            ['emis' => '560', 'school' => 'IMSB (I-V) Boora Bangial', 'name' => 'ATHAR MOHIUDIN', 'email' => 'atharmohiudin1@gmail.com', 'phone' => '0321-5693086'],
            ['emis' => '562', 'school' => 'IMSB (I-VIII) Mohra Kalu', 'name' => 'SHAHZAD PASHA', 'email' => 'shahzadpasha17@gmail.com', 'phone' => '0331-8986629'],
            ['emis' => '563', 'school' => 'IMSB (I-V) D/ Mai Nawab', 'name' => 'SHAHID MAHMOOD', 'email' => 'shahidm.sst@gmail.com', 'phone' => '0300-5593093'],
            ['emis' => '564', 'school' => 'IMSB (I-V) Rajwal', 'name' => 'FAZAL MAHMOOD', 'email' => 'fazalmehmood2911@gmail.com', 'phone' => '0333-5210741'],
            ['emis' => '565', 'school' => 'IMSB (I-V) Kortana', 'name' => 'SHER MUHAMMAD', 'email' => 'chsher70@gmail.com', 'phone' => '0333-5255929'],
            ['emis' => '566', 'school' => 'IMSB (I-VIII) Bhangril Khurd', 'name' => 'JAVED IQBAL', 'email' => 'ji36281@gmail.com', 'phone' => '0336-0055484'],
            ['emis' => '567', 'school' => 'IMSB(I-V) Chak Rawat', 'name' => 'SAJID MAHMOOD', 'email' => 'sajidm1170@gmail.com', 'phone' => '0333-5151674'],
            ['emis' => '568', 'school' => 'IMSB (I-V) Mohri Rawat', 'name' => 'SAJJAD AHMAD', 'email' => 'sajjadahmed8619@gmail.com', 'phone' => '0345-5118688'],
            ['emis' => '569', 'school' => 'IMSB (I-VIII) Koral', 'name' => 'SYED SAJJAD HUSSAIN', 'email' => 'sajjad462125@gmail.com', 'phone' => '0344-5462125'],
            ['emis' => '570', 'school' => 'IMSB (I-VIII) Nara Syedan', 'name' => 'SHAUKAT HAYAT', 'email' => 'shaukathayat149@gmail.com', 'phone' => '0319-5516051'],
            ['emis' => '571', 'school' => 'IMSB(I-V) Chak Kamdar', 'name' => 'MUKHTAR HUSSAIN SHAH', 'email' => 'mukhtar8609@gmail.com', 'phone' => '0300-5081152'],
            ['emis' => '572', 'school' => 'IMSB Sigga (I-V)', 'name' => 'Mr MUHAMAMD TARIQ', 'email' => 'mt12101968@gmail.com', 'phone' => '0336-1531081'],
            ['emis' => '573', 'school' => 'IMSG (I-VIII) CBR Colony', 'name' => 'NOSHABA NAZ', 'email' => 'noshabanaz22@gmail.com', 'phone' => '0334-5310651'],
            ['emis' => '574', 'school' => 'IMSG(I-V) Soan Garden', 'name' => 'GULSHAN BIBI', 'email' => 'gb02959756@gmail.com', 'phone' => '0321-5286659'],
            ['emis' => '575', 'school' => 'IMS (I-V) Gohra Shahan', 'name' => 'AMNA TARIQ', 'email' => 'amnatariq66@yahoo.com', 'phone' => '0300-5326238'],

            // Nilore
            ['emis' => '701', 'school' => 'IMCB (VI-XII), Nilore', 'name' => 'Mr.Shakeel Abbas', 'email' => 'imcbnilore@gmail.com', 'phone' => '3215093673'],
            ['emis' => '702', 'school' => 'IMSB (VI-X), Chirah', 'name' => 'Mr.Kaleem Ullah', 'email' => 'ddoimsbchirah@gmail.com', 'phone' => '3440509033'],
            ['emis' => '703', 'school' => 'IMSB (I-X), Tumair', 'name' => 'Mr. Mehmood Ahmed', 'email' => 'ddoid8808@gmail.com', 'phone' => '3005269614'],
            ['emis' => '704', 'school' => 'IMSB (I-X), Jagiot', 'name' => 'Mr. Abdul Haque', 'email' => 'imsbjagiot8803@gmail.com', 'phone' => '3154808305'],
            ['emis' => '705', 'school' => 'IMSB (VI-X), Jhang Sydan', 'name' => 'Mr. Manzar Bashir', 'email' => 'ddojhangsyedan@gmail.com', 'phone' => '3328319906'],
            ['emis' => '706', 'school' => 'IMSB (VI-X), Tarlai', 'name' => 'Mr. Muhammad Rasheed', 'email' => 'imsb8794@gmail.com', 'phone' => '3066123978'],
            ['emis' => '707', 'school' => 'IMSB (I-X), Khanna Dak', 'name' => 'Mr.Muhammad Riaz', 'email' => 'imsbkhannahdak@gmail.com', 'phone' => '3456311356'],
            ['emis' => '708', 'school' => 'IMCB, Jaba Tali', 'name' => 'Mr. Muhammad Arif', 'email' => 'ddoimcbjaba@gmail.com', 'phone' => '3219855116'],
            ['emis' => '709', 'school' => 'IMSB (I-X), Kirpa', 'name' => 'Mr. Naveed Qaiser', 'email' => 'imsbkirpa@gmail.com', 'phone' => '3709248447'],
            ['emis' => '710', 'school' => 'IMCG (I-XII), Nilore', 'name' => 'Ms.Saima Yaqoob', 'email' => 'ddoid3579@gmail.com', 'phone' => '3459717378'],
            ['emis' => '711', 'school' => 'IMCG (I-XII), Chirah', 'name' => 'Ms. Tehmina Nawaz', 'email' => 'ddoimsg8840@gmail.com', 'phone' => '3119589398'],
            ['emis' => '712', 'school' => 'IMCG (VI-XII), Punjgran', 'name' => 'Ms. Asma Rehman', 'email' => 'imcgpunjgran2014@gmail.com', 'phone' => '3335442612'],
            ['emis' => '713', 'school' => 'IMCG (VI-XII), Tarlai', 'name' => 'Ms.Kousar Parveen', 'email' => 'imcg3547@gmail.com', 'phone' => '3365491344'],
            ['emis' => '714', 'school' => 'IMCG (I-XII), Jagiot', 'name' => 'Ms.Tehmina Zulfiqar', 'email' => 'sobiaabbas39@gmail.com', 'phone' => '3435040662'],
            ['emis' => '715', 'school' => 'IMCG (I-XII), Pehount', 'name' => 'Ms. Bibi Mustafa', 'email' => 'imcgpehount@gmail.com', 'phone' => '3349559733'],
            ['emis' => '716', 'school' => 'IMCG (I-XII), Thanda Pani', 'name' => 'Ms. Sadaf Sarwar', 'email' => 'imcgtp@gmail.com', 'phone' => '3315295550'],
            ['emis' => '717', 'school' => 'IMSB (I-X), Khanna Nai Abadi', 'name' => 'Dr Umer Ameen', 'email' => 'imsbkhanna@gmail.com', 'phone' => '3348697969'],
            ['emis' => '718', 'school' => 'IMSB (I-VIII), Ali Pur', 'name' => 'Mr. Muhammad Shahbaz', 'email' => 'ddoimsb8705@gmail.com', 'phone' => '3365256845'],
            ['emis' => '719', 'school' => 'IMSB (I-VIII), Della', 'name' => 'Mr. Allah Wasya', 'email' => 'imsbdella@gmail.com', 'phone' => '3145194855'],
            ['emis' => '720', 'school' => 'IMSB (I-X), Thanda Pani', 'name' => 'Mr. Raja Muhammad Khalid', 'email' => 'ddoimsb-htp@gmail.com', 'phone' => '3335456292'],
            ['emis' => '721', 'school' => 'IMSB (I-VIII), Pehount', 'name' => 'Mr. Muhammad Rehan', 'email' => 'ddoid8702@gmail.com', 'phone' => '3435516833'],
            ['emis' => '722', 'school' => 'IMSG (I-VIII), Kh. Dak', 'name' => 'Ms. Zahida Naseem', 'email' => 'imsgkhannadak722@gmail.com', 'phone' => '3335528916'],
            ['emis' => '723', 'school' => 'IMSG (I-X), New Shakrial', 'name' => 'Ms. Humaira Babar', 'email' => 'nshakrial@gmail.com', 'phone' => '3028561978'],
            ['emis' => '724', 'school' => 'IMSG (I-VIII), Kalia', 'name' => 'Ms. Farhat Yasmeen', 'email' => 'ddoimsgkalia8715@gmail.com', 'phone' => '3335160768'],
            ['emis' => '725', 'school' => 'IMSG (I-X), Jaba Taili', 'name' => 'Ms. Tehmina Akhter', 'email' => 'ddoid8865@gmail.com', 'phone' => '3335208782'],
            ['emis' => '726', 'school' => 'IMSB (I-VIII), Sohan', 'name' => 'Mr. Malik Muhammad Javied', 'email' => 'imsbddo8601@gmail.com', 'phone' => '3135566777'],
            ['emis' => '727', 'school' => 'IMSB (I-V), Sharifabad', 'name' => 'Mr.Ali Bux', 'email' => 'ddoid1332@gmail.com', 'phone' => '3005173126'],
            ['emis' => '728', 'school' => 'IMSB (I-V), Khadrappar', 'name' => 'Mr. Zaheer Abbas', 'email' => 'ddo8621khadrapper@gmail.com', 'phone' => '3325724572'],
            ['emis' => '729', 'school' => 'IMSB (I-V), Ch. Bangial', 'name' => 'Mr. Amjad Iqbal Satti', 'email' => 'imsb8572@gmail.com', 'phone' => '3335325290'],
            ['emis' => '730', 'school' => 'IMSB (I-V), Chirah', 'name' => 'Mr.Saeed Ahmed', 'email' => 'ddoimsbchirah@gmail.com', 'phone' => '3459462441'],
            ['emis' => '731', 'school' => 'IMSB (I-VIII), Kijnah', 'name' => 'Mr. Muhammad Zubahir', 'email' => 'ddoimsb.kijnah@gmail.com', 'phone' => '3455202108'],
            ['emis' => '732', 'school' => 'IMSB (I-V), Mohara Solina', 'name' => 'Mr. Aftab Hussain', 'email' => 'ddoib1324@gmail.com', 'phone' => '3345046256'],
            ['emis' => '733', 'school' => 'IMSB (I-V), Jhang Syden', 'name' => 'Mr. Ali Nawz Kiflain Shah', 'email' => 'jhangsyedan8613@gmail.com', 'phone' => '3025450784'],
            ['emis' => '734', 'school' => 'IMSB (I-V), Tarlai', 'name' => 'Mr. Nadeem Asif', 'email' => 'ddoid8611@gmail.com', 'phone' => '3315115574'],
            ['emis' => '735', 'school' => 'IMSB (I-V), Mohara', 'name' => 'Mr. Imtiaz Ur Rehman', 'email' => 'ddo8588@gmail.com', 'phone' => '3455259122'],
            ['emis' => '736', 'school' => 'IMSB (I-V), Ara', 'name' => 'Mr. Abbas Hussain Awan', 'email' => 'ddoid8631@gmail.com', 'phone' => '3216850313'],
            ['emis' => '737', 'school' => 'IMSB (I-V), Khanna Kak', 'name' => 'Mr. Dawood Ali', 'email' => 'ddo8579@gmail.com', 'phone' => '3335189239'],
            ['emis' => '738', 'school' => 'IMSB (I-V), Pindmistrian', 'name' => 'Mr. Mudassar Rehman', 'email' => 'pindmistrian@gmail.com', 'phone' => '3005188927'],
            ['emis' => '739', 'school' => 'IMSG (I-V), Shakrial', 'name' => 'Ms. Iffat Naveed', 'email' => 'ddoib2517@gmail.com', 'phone' => '3361532416'],
            ['emis' => '740', 'school' => 'IMSG (I-V), Khanna Nai Abadi', 'name' => 'Ms. Akhtar Parveen', 'email' => 'school8649@gmail.com', 'phone' => '3345330163'],
            ['emis' => '741', 'school' => 'IMSG (I-VIII) No.I, Tarlai', 'name' => 'Ms. Farhana Naseem', 'email' => 'imsgno1tarlai19@gmail.com', 'phone' => '3355010099'],
            ['emis' => '742', 'school' => 'IMSG (I-V) No.2, Tarlai', 'name' => 'Ms. Rehana Kausar', 'email' => 'imsgtarlai@gmail.com', 'phone' => '3345306596'],
            ['emis' => '743', 'school' => 'IMSG (I-V),Tamma', 'name' => 'Ms. Farhana Umair', 'email' => 'imsg8669@gmail.com', 'phone' => '3119545574'],
            ['emis' => '744', 'school' => 'IMSG (I-V), Ali Pur (Mv)', 'name' => 'Ms.Komal Pervaiz', 'email' => 'ddoimsgalipurfrashmv@gmail.com', 'phone' => '3345013261'],
            ['emis' => '745', 'school' => 'IMSG (I-V),Ali Pur Frash', 'name' => 'Ms. Farzana Kousar', 'email' => 'ddoid8630@gmail.com', 'phone' => '3361523702'],
            ['emis' => '746', 'school' => 'IMSG (I-V), Severa', 'name' => 'Ms. Zahida Mehboob', 'email' => 'sevra158@gmail.com', 'phone' => '3115453438'],
            ['emis' => '747', 'school' => 'IMSG (I-V), Chounial Bangial', 'name' => 'Ms. Sobia Akbar', 'email' => 'imsg786@gmail.com', 'phone' => '3318618661'],
            ['emis' => '748', 'school' => 'IMSG (I-V),Herno', 'name' => 'Ms. Shamim Akhter', 'email' => 'ddoid2477@gmail.com', 'phone' => '3005245038'],
            ['emis' => '749', 'school' => 'IMSG (I-X), Darkala', 'name' => 'Ms. Aniza Ambreen', 'email' => 'darkala8864@gmail.com', 'phone' => '3321664044'],
            ['emis' => '750', 'school' => 'IMSG (I-V), Dhok Fathall', 'name' => 'Ms. Mussarat Habib', 'email' => 'imsg7686@gmail.com', 'phone' => '3455105801'],
            ['emis' => '751', 'school' => 'IMSG (I-V),Tumiar', 'name' => 'Ms. Sumaira Bibi', 'email' => 'imsgtumair78@gmail.com', 'phone' => '3319891743'],
            ['emis' => '752', 'school' => 'IMSG (I-VIII), Kijnah', 'name' => 'Ms. Rizwana Kausar', 'email' => 'ddoimsg.kijnah@gmail.com', 'phone' => '3415146229'],
            ['emis' => '754', 'school' => 'IMSG (I-V), Chirah', 'name' => 'Ms. Tehmina Nawaz', 'email' => 'ddoimsg8840@gmail.com', 'phone' => '3119589398'],
            ['emis' => '755', 'school' => 'IMSG (I-VIII), Kalia New', 'name' => 'Ms. Saima Saif', 'email' => 'hussanarasyed@gmail.com', 'phone' => '3131805052'],
            ['emis' => '756', 'school' => 'IMSG (I-V), Jhang Syedan', 'name' => 'Syeda Yasmeen Akhtar', 'email' => 'jhangseydan@gmail.com', 'phone' => '3473289752'],
            ['emis' => '757', 'school' => 'IMSG (I-V), Chappar Ghasota', 'name' => 'Ms. Fouzia Hafeez', 'email' => 'imsgchapperghasota@gmail.com', 'phone' => '3445386861'],
            ['emis' => '758', 'school' => 'IMSG (I-V), Chakhtan', 'name' => 'Ms. Asma Mehboob', 'email' => 'ddoid8635@gmail.com', 'phone' => '3315222501'],
            ['emis' => '759', 'school' => 'IMSG (I-V), Nilore', 'name' => 'Ms.Saima Jabeen', 'email' => 'ddoid8652@gmail.com', 'phone' => '3325904567'],
            ['emis' => '760', 'school' => 'IMSG (I-V), Punjgran', 'name' => 'Ms. Rehana Kousar', 'email' => 'ddoid8673@gmail.com', 'phone' => '3358343936'],
            ['emis' => '761', 'school' => 'IMSG (I-X), Sohan', 'name' => 'Ms. Atifa Jameel', 'email' => 'ddoimsgsohan@gmail.com', 'phone' => '3235919051'],
            ['emis' => '762', 'school' => 'IMSB (I-V), Nilore', 'name' => 'Mr. Naeem Saddique', 'email' => 'imsbnilore@gmail.com', 'phone' => '3215262246'],
            ['emis' => '763', 'school' => 'IMSG (I-V), Ali Pur South', 'name' => 'Ms. Shabana Mushtaq', 'email' => 'ddoib0190@gmail.com', 'phone' => '3015118299'],
            ['emis' => '764', 'school' => 'IMSB (I-V), Sirri', 'name' => 'Mr.Rasheed Ullah', 'email' => 'id8683ddo@gmail.com', 'phone' => '3088432139'],
            ['emis' => '765', 'school' => 'IMSG (I-V), Frash Town', 'name' => 'Ms. Tahira Shaheen', 'email' => 'ddoid8686@gmail.com', 'phone' => '3335641644'],
            ['emis' => '766', 'school' => 'IMCG (I-XII), Kirpa', 'name' => 'Ms. Husan Ara', 'email' => 'ddo3381imcgkirpa@gmail.com', 'phone' => '3315303416'],
            ['emis' => '767', 'school' => 'IMSB (I-V), Biath', 'name' => 'Mr. Zakir Hussain Raja', 'email' => 'ddoib2642@gmail.com', 'phone' => '3455522654'],

            // Tarnol
            ['emis' => '422', 'school' => 'IMSB (I-V) Chahan Mastal', 'name' => 'Bashir Ahmed', 'email' => 'ddoid8571@gmail.com', 'phone' => '0336-5264978'],
            ['emis' => '601', 'school' => 'IMCB Tarnol', 'name' => 'Syed Faisal Bokhari', 'email' => 'ddo3596imcb@gmail.com', 'phone' => '0334-5325379'],
            ['emis' => '602', 'school' => 'IMSB (VI-X) Sangjani', 'name' => 'Tahir Abbas', 'email' => 'ddoid8793@gmail.com', 'phone' => '0333-1635499'],
            ['emis' => '603', 'school' => 'IMSB (I-X) Naugazi', 'name' => 'Dr. Javaid Iqbal', 'email' => 'ddo.imsb.naugazi@gmail.com', 'phone' => '0333-5197397'],
            ['emis' => '604', 'school' => 'IMSB (I-X) I-14', 'name' => 'Kifayat Ullah', 'email' => 'imsbi14@gmail.com', 'phone' => '0333-9492656'],
            ['emis' => '605', 'school' => 'IMSB (VI-X) Noon', 'name' => 'Dr. Muhammad Ishtiaq', 'email' => 'imsb.noon8781@gmail.com', 'phone' => '0306-5043097'],
            ['emis' => '606', 'school' => 'IMSB (I-X) Maira Akku', 'name' => 'Javed Hussain Gul', 'email' => 'ddomairaakku@gmail.com', 'phone' => '0300-3180870'],
            ['emis' => '607', 'school' => 'IMCB Shah Allah Ditta', 'name' => 'Dr. Zafar Iqbal', 'email' => 'ddo8796imsb@gmail.com', 'phone' => '0334-8838005'],
            ['emis' => '608', 'school' => 'IMSB (VI-X) Golra', 'name' => 'Afsar Ali Shah', 'email' => 'ddo8789imsbgolra@gmail.com', 'phone' => '0312-9355536'],
            ['emis' => '609', 'school' => 'IMCB Bhadana Kalan', 'name' => 'Muhammad Arif', 'email' => 'imsbbhadanakalan@gmail.com', 'phone' => '0333-5465984'],
            ['emis' => '610', 'school' => 'IMSG (I-X) Sangjani', 'name' => 'Nadia Mazhar', 'email' => 'ddoimsg8831@gmail.com', 'phone' => '0320-9347909'],
            ['emis' => '611', 'school' => 'IMSG (I-X) Jhangi Syedan', 'name' => 'Saima Maqsood', 'email' => 'imsgjhangi@gmail.com', 'phone' => '0345-5108395'],
            ['emis' => '612', 'school' => 'IMCG Shah Allah Ditta', 'name' => 'Samina Safdar', 'email' => 'ddo3539imcg@gmail.com', 'phone' => '0333-5925000'],
            ['emis' => '613', 'school' => 'IMCG Bhadana Kalan', 'name' => 'Parveen Saif', 'email' => 'imcgbhadanakalan@gmail.com', 'phone' => '0334-8111203'],
            ['emis' => '614', 'school' => 'IMCG Tarnol', 'name' => 'Samina Farooq', 'email' => 'saminazhar76@gmail.com', 'phone' => '0336-5613112'],
            ['emis' => '615', 'school' => 'IMCG Golra', 'name' => 'Shazia Shamim', 'email' => 'ddo.imcg.golra.id3530@gmail.com', 'phone' => '0300-9778925'],
            ['emis' => '616', 'school' => 'IMSG (VI-X)  I-14/3', 'name' => 'Nusrat Farid', 'email' => 'imsg8869@gmail.com', 'phone' => '0300-5319379'],
            ['emis' => '617', 'school' => 'IMSG (I-X) Naugazi', 'name' => 'Farzana Irfan', 'email' => 'ddo8844imsg@gmail.com', 'phone' => '0333-9197301'],
            ['emis' => '618', 'school' => 'IMSG (I-X) Badia Qadir Bukhsh', 'name' => 'Sumaira Liaqat', 'email' => 'imsgbqb@gmail.com', 'phone' => '0307-6208197'],
            ['emis' => '619', 'school' => 'IMSB (I-VIII) Dhoke Jouri', 'name' => 'Ghulam Mujtaba', 'email' => 'imsbdj8706@gmail.com', 'phone' => '0335-0540613'],
            ['emis' => '620', 'school' => 'IMSB (I-X), Dhoke Paracha', 'name' => 'M. Asif Javed', 'email' => 'imsbdhokeparacha@gmail.com', 'phone' => '0300-3512164'],
            ['emis' => '621', 'school' => 'IMSB (I-X) Maira Beri', 'name' => 'Ashfaque Ahmed Mangrio', 'email' => 'ddo8774imsb@gmail.com', 'phone' => '0321-5102102'],
            ['emis' => '622', 'school' => 'IMSB (I-VIII) Chellow', 'name' => 'Mazoor Qadir', 'email' => 'ddo.imsbchellow@gmail.com', 'phone' => '0333-5348918'],
            ['emis' => '623', 'school' => 'IMSG (I-X), Dhoke Jouri', 'name' => 'Rukhsana Aziz', 'email' => 'ddo8722@gmail.com', 'phone' => '0332-1589369'],
            ['emis' => '624', 'school' => 'IMSG (I-X), Pind Paracha', 'name' => 'Sumaira Bi Bi', 'email' => 'imsg624@gmail.com', 'phone' => '0307-6524786'],
            ['emis' => '625', 'school' => 'IMSG (I-X), Noon', 'name' => 'Shazia Mehfooz', 'email' => 'imsgnoon@gmail.com', 'phone' => '0333-5479865'],
            ['emis' => '626', 'school' => 'IMSG (I-X), Dhreak Mohri', 'name' => 'Fozia Rehan', 'email' => 'ddoid255dm@gmail.com', 'phone' => '0333-5061411'],
            ['emis' => '627', 'school' => 'IMSG (I-X) Maira Beri', 'name' => 'Tahira Nusrat', 'email' => 'imsg.mairaberi@gmail.com', 'phone' => '0333-5197999'],
            ['emis' => '628', 'school' => 'IMSG (I-X), Dhoke Paracha', 'name' => 'Nosheen Akhtar', 'email' => 'imsgdhokeparacha@gmail.com', 'phone' => '0334-5782388'],
            ['emis' => '629', 'school' => 'IMSG (I-X), Sarai Kharbuza', 'name' => 'Shahi Nargis', 'email' => 'ddo8742imcgsaraikharboza@gmail.com', 'phone' => '0321-5218075'],
            ['emis' => '630', 'school' => 'IMSB (I-V) Tarnol', 'name' => 'Kashif Jamal', 'email' => 'ddo8616imsb@gmail.com', 'phone' => '0333-5440228'],
            ['emis' => '631', 'school' => 'IMSB (I-V) Tamman', 'name' => 'Munir Ahmed', 'email' => 'ddo8568taman@gmail.com', 'phone' => '0333-5366884'],
            ['emis' => '632', 'school' => 'IMSB (I-V) Sangjani', 'name' => 'Saqib Zulfiqar', 'email' => 'ddo8620sangjani@gmail.com', 'phone' => '0333-5232293'],
            ['emis' => '633', 'school' => 'IMSB (I-V) Dora', 'name' => 'Shoukat Ullah', 'email' => 'imsbdora8576@gmail.com', 'phone' => '0333-8343782'],
            ['emis' => '634', 'school' => 'IMSB (I-V) Sheikhhpur Noon', 'name' => 'Ghalib Abbasi', 'email' => 'imsbsheikhpurnoon@gmail.com', 'phone' => '0333-5306132'],
            ['emis' => '635', 'school' => 'IMSB (I-V) Pindhoon', 'name' => 'Shoukat Sultan', 'email' => 'hmimsbpindhoon@gmail.com', 'phone' => '0334-3131655'],
            ['emis' => '636', 'school' => 'IMSB (I-V) Noon', 'name' => 'Amjad Hussain', 'email' => 'imsb.noon8628@gmail.com', 'phone' => '0333-5176601'],
            ['emis' => '637', 'school' => 'IMSB (I-V) Shah Allah Ditta', 'name' => 'Ghulam Rasool Abid', 'email' => 'ddo8615@gmail.com', 'phone' => '0333-5317864'],
            ['emis' => '638', 'school' => 'IMSB (I-V) Karamabad', 'name' => 'Abdul Hadi Hafeez Ahmad', 'email' => 'imsbkaramabad@gmail.com', 'phone' => '0306-5055866'],
            ['emis' => '639', 'school' => 'IMSB (I-V) Dhoke Lubana', 'name' => 'Hameed Ullah Khan', 'email' => 'hameedullah656@gmail.com', 'phone' => '0348-5006435'],
            ['emis' => '640', 'school' => 'IMSB (I-V) Johd', 'name' => 'Amir Nawas', 'email' => 'imsbjohd@gmail.com', 'phone' => '0311-5350565'],
            ['emis' => '641', 'school' => 'IMSB (I-V) Sarai Kharbuza', 'name' => 'Muhammad Naveed', 'email' => 'imsbsk8595@gmail.com', 'phone' => '0334-8315208'],
            ['emis' => '642', 'school' => 'IMSB (I-V) Pind Parian', 'name' => 'Amir Ameer', 'email' => 'ddo8562pindparian@gmail.com', 'phone' => '0333-5286343'],
            ['emis' => '643', 'school' => 'IMSB (I-V) Dhreak Mohri', 'name' => 'Ayub Babar', 'email' => 'imsbdhreakmohri8607@gmail.com', 'phone' => '0334-2389315'],
            ['emis' => '644', 'school' => 'IMSB (I-V) Seri Saral', 'name' => 'Muhammad Hussain Saeed', 'email' => 'ddoibo102@gmail.com', 'phone' => '0333-5128623'],
            ['emis' => '645', 'school' => 'IMSB (I-V) Bokra', 'name' => 'Abdul Ghaffar Ghangroo', 'email' => 'bokraschool@gmail.com', 'phone' => '0300-9848417'],
            ['emis' => '646', 'school' => 'IMSB (I-V) Jhangi Syedan', 'name' => 'Muhammad Asghar Shahid', 'email' => 'imsbjhangisyedan@gmail.com', 'phone' => '0331-5507997'],
            ['emis' => '647', 'school' => 'IMSB (I-V) Golra', 'name' => 'Afsar Ali Shah', 'email' => 'imsbgolraddo8612@gmail.com', 'phone' => '0312-9355536'],
            ['emis' => '648', 'school' => 'IMSG (I-V) Bekha Syedan', 'name' => 'Maqsoom Gul', 'email' => 'ddo8633@gmail.com', 'phone' => '0306-5280197'],
            ['emis' => '649', 'school' => 'IMSG (I-VIII) Pind Parian', 'name' => 'Gulnaz Parveen', 'email' => 'ddoimsgpindparian@gmail.com', 'phone' => '0332-5198698'],
            ['emis' => '650', 'school' => 'IMSG (I-V) Sheikhpur Noon', 'name' => 'Huma Shahzad', 'email' => 'sheikhpurnoon@gmail.com', 'phone' => '0346-5872060'],
            ['emis' => '651', 'school' => 'IMSG (I-V) Dhoke Hashoo', 'name' => 'Saima Shafiq', 'email' => 'ddo.id8638@gmail.com', 'phone' => '0315-5111096'],
            ['emis' => '652', 'school' => 'IMSG(I-V) Dhoke Suleman', 'name' => 'Anila Noor', 'email' => 'ddoimsg8651@gmail.com', 'phone' => '0314-5127604'],
            ['emis' => '653', 'school' => 'IMSG (I-V) Sarai Madhu', 'name' => 'Shaguta Nasreen', 'email' => 'ddo8639saraimadhu@gmail.com', 'phone' => '0314-5260672'],
            ['emis' => '654', 'school' => 'IMSG (I-V)  I-14/3', 'name' => 'Memoona Khalida', 'email' => 'imsd1346@gmail.com', 'phone' => '0333-5522843'],
            ['emis' => '655', 'school' => 'IMSG (I-X) D-17', 'name' => 'Syeda Wajahat Zahra', 'email' => 'imsd17mvhs@gmail.com', 'phone' => '0364-4939299'],
        ];
    }
}
