<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Institution;
use App\Models\Sector;

class InstitutionSeeder extends Seeder
{
    public function run(): void
    {
        // All 432 schools from EMIS data
        // Sector → school mapping from List_of_Schools_with_EMIS.xlsx
        // Gender and Type pre-set from data
        // Shift: HoI selects when setting up profile
        $schools = [
            ['emis' => 201, 'name' => 'IMCG G-6/1-4', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'Urban-I'],
            ['emis' => 202, 'name' => 'IMSG(VI-X) G-6/1-3', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-I'],
            ['emis' => 203, 'name' => 'IMS (I-V) G-6/1-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 204, 'name' => 'IMS (I-V) G-6/1-3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 205, 'name' => 'IMS(I-V) G-6/1-4', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 206, 'name' => 'IMSG(VI-X) G-6/2-2', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-I'],
            ['emis' => 207, 'name' => 'IMS(I-V) G-6/2-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 208, 'name' => 'IMS(I-V) G-6/2-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 209, 'name' => 'IMS(I-V) G-6/2-4', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 210, 'name' => 'IMS(I-V) G-6/2-5', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 211, 'name' => 'IMS(I-V) G-6/3-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 212, 'name' => 'IMS(I-V) G-6/3-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 213, 'name' => 'IMS(I-V) G-6/3-3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 214, 'name' => 'IMS(I-V) G-6/3-4', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 215, 'name' => 'IMS(I-V) G-6/4-3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 216, 'name' => 'IMS(I-V) G-6/4-4', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 217, 'name' => 'IMS(I-V) G-6/4-5', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 218, 'name' => 'IMSG(VI-X) G-6/4-2', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-I'],
            ['emis' => 219, 'name' => 'IMCG F-6/2', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-I'],
            ['emis' => 220, 'name' => 'IMS(I-V) F-6/1-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 221, 'name' => 'IMS(I-V) F-6/1-3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 222, 'name' => 'IMS(I-V) F-6/2-3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 223, 'name' => 'IMS(I-V) F-6/2-4', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 224, 'name' => 'IMS(I-V) F-6/3-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 225, 'name' => 'IMS(I-V) F-6/3-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 226, 'name' => 'IMS(I-V) F-6/4-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 227, 'name' => 'IMSG(VI-X) F-6/4-2', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-I'],
            ['emis' => 228, 'name' => 'IMSG(VI-VIII) F-6/3-3', 'gender' => 'girls', 'type' => 'VI-VIII', 'sector' => 'Urban-I'],
            ['emis' => 229, 'name' => 'IMS(I-V) F-6/4-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 230, 'name' => 'IMCG F-7/3', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-I'],
            ['emis' => 231, 'name' => 'IMCB F-7/4', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-I'],
            ['emis' => 232, 'name' => 'IMS(I-V) F-7/1-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 233, 'name' => 'IMS(I-V) F-7/1-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 234, 'name' => 'IMS(I-V) F-7/2-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 235, 'name' => 'IMS(I-VIII) F-7/2-2', 'gender' => 'co_education', 'type' => 'I-VIII', 'sector' => 'Urban-I'],
            ['emis' => 236, 'name' => 'IMS(I-V) F-7/3-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 237, 'name' => 'IMSG(VI-X) F-7/3-2', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-I'],
            ['emis' => 238, 'name' => 'IMS(I-V) F-7/4-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 239, 'name' => 'IMS(I-V) F-7/4-3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 240, 'name' => 'IMCG F-8/1', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-I'],
            ['emis' => 241, 'name' => 'IMCB F-8/4', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-I'],
            ['emis' => 242, 'name' => 'IMS(I-V) F-8/1-3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 243, 'name' => 'IMS(I-V) F-8/2-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 244, 'name' => 'IMS(I-V) F-8/2-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 245, 'name' => 'IMSG(VI-X) F-8/3-2', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-I'],
            ['emis' => 246, 'name' => 'IMS(I-V) F-8/3-3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 247, 'name' => 'IMS(I-V) F-8/4-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 248, 'name' => 'IMS(I-V) F-8/4-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 249, 'name' => 'IMSG(VI-VIII) F-8/4-3', 'gender' => 'girls', 'type' => 'VI-VIII', 'sector' => 'Urban-I'],
            ['emis' => 250, 'name' => 'IMS(I-V) F-9/1-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 251, 'name' => 'IMS(I-V) F-9/2-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 252, 'name' => 'IMS(I-V) F-9/3-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 253, 'name' => 'IMS(I-V) F-9/4-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 254, 'name' => 'IMS(I-V) F-9/4-3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 255, 'name' => 'IMS(I-V) F-10/1-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 256, 'name' => 'IMS(I-V) F-10/1-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 257, 'name' => 'IMS(I-V) F-10/2-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 258, 'name' => 'IMS(I-V) F-10/3-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 259, 'name' => 'IMS(I-V) F-10/4-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 260, 'name' => 'IMS(I-V) F-11/1-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 261, 'name' => 'IMS(I-V) F-11/1-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 262, 'name' => 'IMS(I-V) F-11/2-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 263, 'name' => 'IMS(I-V) F-11/3-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 264, 'name' => 'IMS(I-V) F-11/4-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-I'],
            ['emis' => 265, 'name' => 'IMCG F-10/A', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-I'],
            ['emis' => 266, 'name' => 'IMCB F-10/A', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-I'],
            ['emis' => 267, 'name' => 'IMSG(VI-X) F-10/3-2', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-I'],
            ['emis' => 268, 'name' => 'IMSG(VI-VIII) F-11/2-2', 'gender' => 'girls', 'type' => 'VI-VIII', 'sector' => 'Urban-I'],
            ['emis' => 269, 'name' => 'ICG F-6/2', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-I'],
            ['emis' => 270, 'name' => 'ICB G-6/3', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-I'],
            ['emis' => 271, 'name' => 'IMCG G-7/1-2', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 272, 'name' => 'IMCB G-7/2-2', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 273, 'name' => 'IMS(I-V) G-7/1-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 274, 'name' => 'IMS(I-V) G-7/1-3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 275, 'name' => 'IMS(I-V) G-7/2-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 276, 'name' => 'IMS(I-V) G-7/2-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 277, 'name' => 'IMS(I-V) G-7/3-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 278, 'name' => 'IMS(I-V) G-7/3-3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 279, 'name' => 'IMS(I-V) G-7/4-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 280, 'name' => 'IMS(I-V) G-7/4-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 281, 'name' => 'IMCG G-8/1-2', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 282, 'name' => 'IMCB G-8/1-3', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 283, 'name' => 'IMS(I-V) G-8/1-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 284, 'name' => 'IMS(I-V) G-8/2-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 285, 'name' => 'IMS(I-V) G-8/2-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 286, 'name' => 'IMS(I-V) G-8/3-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 287, 'name' => 'IMS(I-V) G-8/3-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 288, 'name' => 'IMSG(VI-X) G-8/3-3', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-II'],
            ['emis' => 289, 'name' => 'IMS(I-V) G-8/4-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 290, 'name' => 'IMS(I-V) G-8/4-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 291, 'name' => 'IMCG G-9/1', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 292, 'name' => 'IMCB G-9/3', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 293, 'name' => 'IMS(I-V) G-9/1-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 294, 'name' => 'IMS(I-V) G-9/1-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 295, 'name' => 'IMS(I-V) G-9/2-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 296, 'name' => 'IMS(I-V) G-9/2-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 297, 'name' => 'IMS(I-V) G-9/3-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 298, 'name' => 'IMSG(VI-X) G-9/4-2', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-II'],
            ['emis' => 299, 'name' => 'IMS(I-V) G-9/4-3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 300, 'name' => 'IMCG G-10/4', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 301, 'name' => 'IMCB G-10/1', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 302, 'name' => 'IMS(I-V) G-10/1-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 303, 'name' => 'IMS(I-V) G-10/1-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 304, 'name' => 'IMS(I-V) G-10/2-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 305, 'name' => 'IMS(I-V) G-10/2-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 306, 'name' => 'IMS(I-V) G-10/3-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 307, 'name' => 'IMSG(VI-X) G-10/3-2', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-II'],
            ['emis' => 308, 'name' => 'IMS(I-V) G-10/4-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 309, 'name' => 'IMS(I-V) G-10/4-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 310, 'name' => 'IMCG G-11/1', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 311, 'name' => 'IMCB G-11/4', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 312, 'name' => 'IMS(I-V) G-11/1-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 313, 'name' => 'IMS(I-V) G-11/1-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 314, 'name' => 'IMS(I-V) G-11/2-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 315, 'name' => 'IMS(I-V) G-11/3-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 316, 'name' => 'IMS(I-V) G-11/4-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 317, 'name' => 'IMS(I-V) G-12/1-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 318, 'name' => 'IMS(I-V) G-12/1-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 319, 'name' => 'IMS(I-V) G-13/1-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 320, 'name' => 'IMS(I-V) G-13/2-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 321, 'name' => 'IMS(I-VIII) G-13/2-2', 'gender' => 'co_education', 'type' => 'I-VIII', 'sector' => 'Urban-II'],
            ['emis' => 322, 'name' => 'IMCG I-8/1', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 323, 'name' => 'IMCB I-8/2', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 324, 'name' => 'IMS(I-V) I-8/1-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 325, 'name' => 'IMS(I-V) I-8/1-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 326, 'name' => 'IMS(I-V) I-8/2-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 327, 'name' => 'IMS(I-V) I-8/2-3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 328, 'name' => 'IMS(I-V) I-8/3-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 329, 'name' => 'IMS(I-V) I-8/3-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 330, 'name' => 'IMS(I-V) I-8/4-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 331, 'name' => 'IMS(I-VIII) H-8/1', 'gender' => 'co_education', 'type' => 'I-VIII', 'sector' => 'Urban-II'],
            ['emis' => 332, 'name' => 'IMCG I-9/1', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 333, 'name' => 'IMCB I-9/4', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 334, 'name' => 'IMS(I-V) I-9/1-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 335, 'name' => 'IMS(I-V) I-9/1-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 336, 'name' => 'IMS(I-V) I-9/2-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 337, 'name' => 'IMS(I-V) I-9/2-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 338, 'name' => 'IMS(I-V) I-9/3-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 339, 'name' => 'IMS(I-V) I-9/3-2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 340, 'name' => 'IMS(I-V) I-9/4-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 341, 'name' => 'IMS(I-V) H-9/1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 342, 'name' => 'IMCG I-10/1', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 343, 'name' => 'IMCB I-10/4', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 344, 'name' => 'IMS(I-V) I-10/1-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 345, 'name' => 'IMS(I-V) I-10/2-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 346, 'name' => 'IMS(I-V) I-10/3-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 347, 'name' => 'IMS(I-V) I-10/4-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 348, 'name' => 'IMS(I-V) H-10/1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 349, 'name' => 'IMCG I-11/1', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 350, 'name' => 'IMCB I-11/4', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-II'],
            ['emis' => 351, 'name' => 'IMS(I-V) I-11/1-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 352, 'name' => 'IMS(I-V) I-11/2-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 353, 'name' => 'IMS(I-V) I-11/3-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 354, 'name' => 'IMS(I-V) I-11/4-1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 355, 'name' => 'IMS(I-V) H-11/1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Urban-II'],
            ['emis' => 356, 'name' => 'IMS(I-VIII) I-12/1', 'gender' => 'co_education', 'type' => 'I-VIII', 'sector' => 'Urban-II'],
            ['emis' => 357, 'name' => 'IMS(I-VIII) H-13/1', 'gender' => 'co_education', 'type' => 'I-VIII', 'sector' => 'Urban-II'],
            ['emis' => 401, 'name' => 'IMCG Tarnol', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Tarnol'],
            ['emis' => 402, 'name' => 'IMCB Tarnol', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Tarnol'],
            ['emis' => 403, 'name' => 'GPS Golra Mor', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 404, 'name' => 'GPS Humayun Colony', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 405, 'name' => 'GMS Golra Sharif', 'gender' => 'co_education', 'type' => 'I-VIII', 'sector' => 'Tarnol'],
            ['emis' => 406, 'name' => 'GPS Phulgran', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 407, 'name' => 'GHS Tarnol', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Tarnol'],
            ['emis' => 408, 'name' => 'GGHS Tarnol', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Tarnol'],
            ['emis' => 409, 'name' => 'GPS Tarnol No.1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 410, 'name' => 'GPS Tarnol No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 411, 'name' => 'GPS Pind Begwal', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 412, 'name' => 'GPS Alipur', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 413, 'name' => 'GPS Badhana Kalan', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 414, 'name' => 'GHS Phulgran', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Tarnol'],
            ['emis' => 415, 'name' => 'GGPS Tarlai', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 416, 'name' => 'GPS Tarlai Kalan', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 417, 'name' => 'GGMS Tarlai Kalan', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Tarnol'],
            ['emis' => 418, 'name' => 'GHS Tarlai Kalan', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Tarnol'],
            ['emis' => 419, 'name' => 'GPS Jhangi Syedan', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 420, 'name' => 'GGPS Shah Allah Ditta', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 421, 'name' => 'GPS Shah Allah Ditta', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 422, 'name' => 'GPS Sarai Kharbuza', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 423, 'name' => 'GGPS Alipur', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 424, 'name' => 'GGPS Badhana Kalan', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 425, 'name' => 'GMS Tarnol', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Tarnol'],
            ['emis' => 426, 'name' => 'GPS Chak Begwal', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 427, 'name' => 'GPS Mohri', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 428, 'name' => 'GHS Golra Sharif', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Tarnol'],
            ['emis' => 429, 'name' => 'GGHS Golra Sharif', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Tarnol'],
            ['emis' => 430, 'name' => 'GPS Humak', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 431, 'name' => 'GGPS Humak', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 432, 'name' => 'GHS Humak', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Tarnol'],
            ['emis' => 433, 'name' => 'GGHS Humak', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Tarnol'],
            ['emis' => 434, 'name' => 'GPS Khana Dak', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 435, 'name' => 'GGPS Khana Dak', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 436, 'name' => 'GMS Khana Dak', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Tarnol'],
            ['emis' => 437, 'name' => 'GGMS Khana Dak', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Tarnol'],
            ['emis' => 438, 'name' => 'GPS Pind Malkan', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 439, 'name' => 'GPS Mauza Tumair', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 440, 'name' => 'GGPS Tumair', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 441, 'name' => 'GMS Tumair', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Tarnol'],
            ['emis' => 442, 'name' => 'GGMS Tumair', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Tarnol'],
            ['emis' => 443, 'name' => 'GHS Koral', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Tarnol'],
            ['emis' => 444, 'name' => 'GGHS Koral', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Tarnol'],
            ['emis' => 445, 'name' => 'GPS Koral', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 446, 'name' => 'GGPS Koral', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 447, 'name' => 'GMS Koral', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Tarnol'],
            ['emis' => 448, 'name' => 'GGMS Koral', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Tarnol'],
            ['emis' => 449, 'name' => 'GPS Charah', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 450, 'name' => 'GGPS Charah', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 451, 'name' => 'GMS Charah', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Tarnol'],
            ['emis' => 452, 'name' => 'GGMS Charah', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Tarnol'],
            ['emis' => 453, 'name' => 'GHS Charah', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Tarnol'],
            ['emis' => 454, 'name' => 'GGHS Charah', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Tarnol'],
            ['emis' => 455, 'name' => 'GPS Kirpa', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 456, 'name' => 'GGPS Kirpa', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol'],
            ['emis' => 457, 'name' => 'GMS Kirpa', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Tarnol'],
            ['emis' => 458, 'name' => 'GGMS Kirpa', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Tarnol'],
            ['emis' => 459, 'name' => 'GHS Kirpa', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Tarnol'],
            ['emis' => 460, 'name' => 'GGHS Kirpa', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Tarnol'],
            ['emis' => 501, 'name' => 'IMCG Sihala', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Sihala'],
            ['emis' => 502, 'name' => 'IMCB Sihala', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Sihala'],
            ['emis' => 503, 'name' => 'GPS Sihala No.1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 504, 'name' => 'GGPS Sihala', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 505, 'name' => 'GMS Sihala', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Sihala'],
            ['emis' => 506, 'name' => 'GGMS Sihala', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala'],
            ['emis' => 507, 'name' => 'GHS Sihala', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 508, 'name' => 'GGHS Sihala', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 509, 'name' => 'GPS Lohi Bhar', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 510, 'name' => 'GGPS Lohi Bhar', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 511, 'name' => 'GMS Lohi Bhar', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Sihala'],
            ['emis' => 512, 'name' => 'GGMS Lohi Bhar', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala'],
            ['emis' => 513, 'name' => 'GHS Lohi Bhar', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 514, 'name' => 'GGHS Lohi Bhar', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 515, 'name' => 'GPS Darwala', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 516, 'name' => 'GGPS Darwala', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 517, 'name' => 'GMS Darwala', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Sihala'],
            ['emis' => 518, 'name' => 'GGMS Darwala', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala'],
            ['emis' => 519, 'name' => 'GHS Darwala', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 520, 'name' => 'GGHS Darwala', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 521, 'name' => 'GPS Rawat No.1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 522, 'name' => 'GGPS Rawat', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 523, 'name' => 'GMS Rawat', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Sihala'],
            ['emis' => 524, 'name' => 'GGMS Rawat', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala'],
            ['emis' => 525, 'name' => 'GHS Rawat', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 526, 'name' => 'GGHS Rawat', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 527, 'name' => 'GPS Chak Shehzad', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 528, 'name' => 'GGPS Chak Shehzad', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 529, 'name' => 'GMS Chak Shehzad', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Sihala'],
            ['emis' => 530, 'name' => 'GGMS Chak Shehzad', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala'],
            ['emis' => 531, 'name' => 'GHS Chak Shehzad', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 532, 'name' => 'GGHS Chak Shehzad', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 533, 'name' => 'GPS Sohan', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 534, 'name' => 'GGPS Sohan', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 535, 'name' => 'GMS Sohan', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Sihala'],
            ['emis' => 536, 'name' => 'GGMS Sohan', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala'],
            ['emis' => 537, 'name' => 'GHS Sohan', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 538, 'name' => 'GGHS Sohan', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 539, 'name' => 'GPS Alipur Farmana', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 540, 'name' => 'GHS Alipur Farmana', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 541, 'name' => 'GGHS Alipur Farmana', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 542, 'name' => 'GPS Mughal', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 543, 'name' => 'GGPS Mughal', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 544, 'name' => 'GMS Mughal', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Sihala'],
            ['emis' => 545, 'name' => 'GGMS Mughal', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala'],
            ['emis' => 546, 'name' => 'GHS Mughal', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 547, 'name' => 'GGHS Mughal', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 548, 'name' => 'GPS Kuri', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 549, 'name' => 'GGPS Kuri', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala'],
            ['emis' => 550, 'name' => 'GMS Kuri', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Sihala'],
            ['emis' => 551, 'name' => 'GGMS Kuri', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala'],
            ['emis' => 552, 'name' => 'GHS Kuri', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 553, 'name' => 'GGHS Kuri', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala'],
            ['emis' => 601, 'name' => 'IMCG Nilore', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Nilore'],
            ['emis' => 602, 'name' => 'IMCB Nilore', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Nilore'],
            ['emis' => 603, 'name' => 'GPS Nilore No.1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 604, 'name' => 'GGPS Nilore', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 605, 'name' => 'GMS Nilore', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Nilore'],
            ['emis' => 606, 'name' => 'GGMS Nilore', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Nilore'],
            ['emis' => 607, 'name' => 'GHS Nilore', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Nilore'],
            ['emis' => 608, 'name' => 'GGHS Nilore', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Nilore'],
            ['emis' => 609, 'name' => 'GPS Rawat No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 610, 'name' => 'GPS Humak No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 611, 'name' => 'GPS Koral No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 612, 'name' => 'GPS Noon No.1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 613, 'name' => 'GGPS Noon', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 614, 'name' => 'GMS Noon', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Nilore'],
            ['emis' => 615, 'name' => 'GGMS Noon', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Nilore'],
            ['emis' => 616, 'name' => 'GHS Noon', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Nilore'],
            ['emis' => 617, 'name' => 'GGHS Noon', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Nilore'],
            ['emis' => 618, 'name' => 'GPS Malpur', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 619, 'name' => 'GGPS Malpur', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 620, 'name' => 'GMS Malpur', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Nilore'],
            ['emis' => 621, 'name' => 'GGMS Malpur', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Nilore'],
            ['emis' => 622, 'name' => 'GHS Malpur', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Nilore'],
            ['emis' => 623, 'name' => 'GGHS Malpur', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Nilore'],
            ['emis' => 624, 'name' => 'GPS Saidpur', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 625, 'name' => 'GGPS Saidpur', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 626, 'name' => 'GMS Saidpur', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Nilore'],
            ['emis' => 627, 'name' => 'GGMS Saidpur', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Nilore'],
            ['emis' => 628, 'name' => 'GHS Saidpur', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Nilore'],
            ['emis' => 629, 'name' => 'GGHS Saidpur', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Nilore'],
            ['emis' => 630, 'name' => 'GPS Noorpur Shahan', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 631, 'name' => 'GGPS Noorpur Shahan', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 632, 'name' => 'GMS Noorpur Shahan', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Nilore'],
            ['emis' => 633, 'name' => 'GGMS Noorpur Shahan', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Nilore'],
            ['emis' => 634, 'name' => 'GHS Noorpur Shahan', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Nilore'],
            ['emis' => 635, 'name' => 'GGHS Noorpur Shahan', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Nilore'],
            ['emis' => 636, 'name' => 'GPS Rawal Margala', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 637, 'name' => 'GGPS Rawal Margala', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 638, 'name' => 'GMS Rawal Margala', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Nilore'],
            ['emis' => 639, 'name' => 'GGMS Rawal Margala', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Nilore'],
            ['emis' => 640, 'name' => 'GHS Rawal Margala', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Nilore'],
            ['emis' => 641, 'name' => 'GGHS Rawal Margala', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Nilore'],
            ['emis' => 642, 'name' => 'GPS Banigala', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 643, 'name' => 'GGPS Banigala', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore'],
            ['emis' => 644, 'name' => 'GMS Banigala', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Nilore'],
            ['emis' => 645, 'name' => 'GGMS Banigala', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Nilore'],
            ['emis' => 646, 'name' => 'GHS Banigala', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Nilore'],
            ['emis' => 647, 'name' => 'GGHS Banigala', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Nilore'],
            ['emis' => 701, 'name' => 'IMCG Bharakahu', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'B.K'],
            ['emis' => 702, 'name' => 'IMCB Bharakahu', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'B.K'],
            ['emis' => 703, 'name' => 'GPS Bharakahu No.1', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 704, 'name' => 'GGPS Bharakahu', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 705, 'name' => 'GMS Bharakahu', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'B.K'],
            ['emis' => 706, 'name' => 'GGMS Bharakahu', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'B.K'],
            ['emis' => 707, 'name' => 'GHS Bharakahu', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'B.K'],
            ['emis' => 708, 'name' => 'GGHS Bharakahu', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K'],
            ['emis' => 709, 'name' => 'GPS Kot Hathial', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 710, 'name' => 'GGPS Kot Hathial', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 711, 'name' => 'GMS Kot Hathial', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'B.K'],
            ['emis' => 712, 'name' => 'GGMS Kot Hathial', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'B.K'],
            ['emis' => 713, 'name' => 'GHS Kot Hathial', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'B.K'],
            ['emis' => 714, 'name' => 'GGHS Kot Hathial', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K'],
            ['emis' => 715, 'name' => 'GPS Phulgran No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 716, 'name' => 'GPS Pind Begwal No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 717, 'name' => 'GPS Tumair No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 718, 'name' => 'GPS Charah No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 719, 'name' => 'GPS Kirpa No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 720, 'name' => 'GPS Mughal No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 721, 'name' => 'GPS Rawat No.3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 722, 'name' => 'GPS Humak No.3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 723, 'name' => 'GPS Koral No.3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 724, 'name' => 'GPS Sohan No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 725, 'name' => 'GPS Alipur No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 726, 'name' => 'GPS Chak Shehzad No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 727, 'name' => 'GPS Lohi Bhar No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 728, 'name' => 'GPS Darwala No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 729, 'name' => 'GPS Kuri No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 730, 'name' => 'GPS Noorpur Shahan No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 731, 'name' => 'GPS Saidpur No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 732, 'name' => 'GPS Malpur No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 733, 'name' => 'GPS Rawal Margala No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 734, 'name' => 'GPS Banigala No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 735, 'name' => 'GPS Nilore No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 736, 'name' => 'GPS Tarnol No.3', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 737, 'name' => 'GPS Sihala No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 738, 'name' => 'GPS Golra Sharif No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 739, 'name' => 'GPS Jhangi Syedan No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 740, 'name' => 'GPS Shah Allah Ditta No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 741, 'name' => 'GPS Sarai Kharbuza No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 742, 'name' => 'GPS Badhana Kalan No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 743, 'name' => 'GPS Khana Dak No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 744, 'name' => 'GPS Tarlai Kalan No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 745, 'name' => 'GPS Alipur Farmana No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 746, 'name' => 'GPS Noon No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 747, 'name' => 'GPS Golra Mor No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 748, 'name' => 'GPS Humayun Colony No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 749, 'name' => 'GPS Mauza Tumair No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 750, 'name' => 'GPS Pind Malkan No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 751, 'name' => 'GPS Mohri No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 752, 'name' => 'GPS Chak Begwal No.2', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 753, 'name' => 'GPS Bhara Kahu', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 754, 'name' => 'GGPS Bhara Kahu', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 755, 'name' => 'GMS Bhara Kahu', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'B.K'],
            ['emis' => 756, 'name' => 'GGMS Bhara Kahu', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'B.K'],
            ['emis' => 757, 'name' => 'GHS Bhara Kahu', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'B.K'],
            ['emis' => 758, 'name' => 'GGHS Bhara Kahu', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K'],
            ['emis' => 759, 'name' => 'GPS Korang', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 760, 'name' => 'GGPS Korang', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 761, 'name' => 'GMS Korang', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'B.K'],
            ['emis' => 762, 'name' => 'GGMS Korang', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'B.K'],
            ['emis' => 763, 'name' => 'GHS Korang', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'B.K'],
            ['emis' => 764, 'name' => 'GGHS Korang', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K'],
            ['emis' => 765, 'name' => 'GPS Bari Imam', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 766, 'name' => 'GGPS Bari Imam', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 767, 'name' => 'GMS Bari Imam', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'B.K'],
            ['emis' => 768, 'name' => 'GGMS Bari Imam', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'B.K'],
            ['emis' => 769, 'name' => 'GHS Bari Imam', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'B.K'],
            ['emis' => 770, 'name' => 'GGHS Bari Imam', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K'],
            ['emis' => 771, 'name' => 'GPS Maira Sumbal', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 772, 'name' => 'GGPS Maira Sumbal', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 773, 'name' => 'GMS Maira Sumbal', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'B.K'],
            ['emis' => 774, 'name' => 'GGMS Maira Sumbal', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'B.K'],
            ['emis' => 775, 'name' => 'GHS Maira Sumbal', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'B.K'],
            ['emis' => 776, 'name' => 'GGHS Maira Sumbal', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K'],
            ['emis' => 777, 'name' => 'GPS Jaffar', 'gender' => 'co_education', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 778, 'name' => 'GGPS Jaffar', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K'],
            ['emis' => 779, 'name' => 'GMS Jaffar', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'B.K'],
            ['emis' => 780, 'name' => 'GGMS Jaffar', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'B.K'],
            ['emis' => 781, 'name' => 'GHS Jaffar', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'B.K'],
            ['emis' => 782, 'name' => 'GGHS Jaffar', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K'],
        ];

        $sectorCache = [];

        foreach ($schools as $school) {
            $sectorName = $school['sector'];

            // Cache sector lookups
            if (!isset($sectorCache[$sectorName])) {
                $sectorCache[$sectorName] = Sector::where('name', $sectorName)->first();
            }

            $sector = $sectorCache[$sectorName];

            if (!$sector) {
                $this->command->warn("Sector not found: {$sectorName} for school {$school['name']}");
                continue;
            }

            $institution = Institution::firstOrCreate(
                ['code' => (string)$school['emis']],
                    [

                    'name'               => $school['name'],
                    'sector_id'          => $sector->id,
                    'uc_id'              => null,
                    'type'               => $school['type'],
                    'gender'             => $school['gender'],
                    'shift'              => 'morning',
                    'admission_status'   => 'not_started',
                    'has_matric_tech'    => false,
                    'has_transport'      => false,
                    'has_meal_program'   => false,
                    'has_evening_classes'=> false,
                    'is_active'          => true,
                ]
            );

            // Set Cambridge flag
            if ($institution->isCambridgeEligible()) {
                \DB::table('institutions')
                    ->where('id', $institution->id)
                    ->update(['is_cambridge' => true]);
            }
        }

        $this->command->info('432 institutions seeded successfully.');
    }
}
