<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Institution;
use App\Models\Sector;

class InstitutionSeeder extends Seeder
{
    public function run(): void
    {
        // All 432 schools from EMIS data
        // Sector → school mapping from List_of_Schools_with_EMIS.xlsx
        // Gender and Type pre-set from data
        // Shift: HoI selects when setting up profile
        $schools = [
            ['emis' => 201, 'name' => 'IMCG G-6/1-4', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'Urban-I', 'UC' => 'UC-26 Sector G-6/1'],
            ['emis' => 202, 'name' => 'IMSG(VI-X) G-6/1-3', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-I', 'UC' => 'UC-26 Sector G-6/1'],
            ['emis' => 203, 'name' => 'IMS (I-V) G-6/1-1', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-26 Sector G-6/1'],
            ['emis' => 204, 'name' => 'IMS (I-V) G-6/1-3', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-26 Sector G-6/1'],
            ['emis' => 205, 'name' => 'IMS(I-V) G-6/1-4', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-26 Sector G-6/1'],
            ['emis' => 206, 'name' => 'IMS(I-V) G-6/4', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-27 Sector G-6/2'],
            ['emis' => 207, 'name' => 'IMSG(VI-X) G-6/2', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-I', 'UC' => 'UC-27 Sector G-6/2'],
            ['emis' => 208, 'name' => 'IMS(I-V) G-6/2 Caf√© Iram', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-27 Sector G-6/2'],
            ['emis' => 209, 'name' => 'IMSG(I-VIII) G-6/2', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Urban-I', 'UC' => 'UC-27 Sector G-6/2'],
            ['emis' => 210, 'name' => 'IMS(I-V) G-6/2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-27 Sector G-6/2'],
            ['emis' => 211, 'name' => 'IMSG (I-X) P.E. CLY G-5', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Urban-I', 'UC' => 'UC-25 Sector F-6'],
            ['emis' => 212, 'name' => 'IMS(I-V) G-6/1-2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-26 Sector G-6/1'],
            ['emis' => 213, 'name' => 'IMSG(VI-X) G-7/1', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-I', 'UC' => 'UC-31 Sector G-7/1 G-7/2'],
            ['emis' => 214, 'name' => 'IMSG(VI-X) G-7/2', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-I', 'UC' => 'UC-31 Sector G-7/1 G-7/2'],
            ['emis' => 215, 'name' => 'IMSG (I-VIII) G-7/3-2', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Urban-I', 'UC' => 'UC-30 Sector G-7/3 G-7/4'],
            ['emis' => 216, 'name' => 'IMS(I-V) G-7/1', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-31 Sector G-7/1 G-7/2'],
            ['emis' => 217, 'name' => 'IMS(I-V) G-7/4', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-30 Sector G-7/3 G-7/4'],
            ['emis' => 218, 'name' => 'IMSG (I-VIII) G-7/3-4', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Urban-I', 'UC' => 'UC-30 Sector G-7/3 G-7/4'],
            ['emis' => 219, 'name' => 'IMS(I-V) G-7/3-1', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-30 Sector G-7/3 G-7/4'],
            ['emis' => 220, 'name' => 'IMS (I-V) G-7/3-3', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-30 Sector G-7/3 G-7/4'],
            ['emis' => 221, 'name' => 'IMSG (I-VIII) F-7/1', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 222, 'name' => 'IMS(I-V) No.1 G-7/2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-31 Sector G-7/1 G-7/2'],
            ['emis' => 223, 'name' => 'IMSG(VI-X) F-7/2', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 224, 'name' => 'IMSG(VI-X) F-6/1', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-I', 'UC' => 'UC-25 Sector F-6'],
            ['emis' => 225, 'name' => 'IMSG (I-VIII) F-7/4', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 226, 'name' => 'IMS(I-V) F-6/4', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-25 Sector F-6'],
            ['emis' => 227, 'name' => 'IMSG (I-X) P.M. Colony G-5', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Urban-I', 'UC' => 'UC-25 Sector F-6'],
            ['emis' => 228, 'name' => 'IMS(I-V) F-6/1', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-25 Sector F-6'],
            ['emis' => 229, 'name' => 'IMS(I-V) F-6/3', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 230, 'name' => 'IMS (I-V), F-7/2-4', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 231, 'name' => 'IMS(I-V) F-7/2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 232, 'name' => 'IMSB (I-X) P.M. Colony G-5', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Urban-I', 'UC' => 'UC-25 Sector F-6'],
            ['emis' => 233, 'name' => 'IMSG(VI-X) E-8/3,', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-I', 'UC' => 'UC-40 I-8 & H8'],
            ['emis' => 234, 'name' => 'IMS(I-V) No.1 E-8', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-40 I-8 & H8'],
            ['emis' => 235, 'name' => 'IMS(I-V) No.2 E-8', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 236, 'name' => 'IMSG(I-X)  E-9', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 237, 'name' => 'IMS(I-V)  E-7/4', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 238, 'name' => 'IMCG G-8/4', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'Urban-I', 'UC' => 'UC-32 Sector G-8/3 G-8/4'],
            ['emis' => 239, 'name' => 'IMSG(VI-X) G-8/2', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-I', 'UC' => 'UC-33 Sector G-8/1 G-8/2'],
            ['emis' => 240, 'name' => 'IMSG (I-VIII) G-8/4', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Urban-I', 'UC' => 'UC-32 Sector G-8/3 G-8/4'],
            ['emis' => 241, 'name' => 'IMS(I-V) No.1 G-8/4', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-32 Sector G-8/3 G-8/4'],
            ['emis' => 242, 'name' => 'IMS(I-V) No.2  G-8/4', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-32 Sector G-8/3 G-8/4'],
            ['emis' => 243, 'name' => 'IMS(I-V) No.1  G-8/1', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-33 Sector G-8/1 G-8/2'],
            ['emis' => 244, 'name' => 'IMS(I-V) No.2  G-8/1', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-33 Sector G-8/1 G-8/2'],
            ['emis' => 245, 'name' => 'IMS(I-V) No.3  G-8/1', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-33 Sector G-8/1 G-8/2'],
            ['emis' => 246, 'name' => 'IMS(I-V) No.1  G-8/2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-33 Sector G-8/1 G-8/2'],
            ['emis' => 247, 'name' => 'IMS(I-V) No.2  G-8/2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-33 Sector G-8/1 G-8/2'],
            ['emis' => 248, 'name' => 'IMS(I-V) PIMS  G-8/3', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-33 Sector G-8/1 G-8/2'],
            ['emis' => 249, 'name' => 'IMS(I-V) F-8/2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 250, 'name' => 'IMSG(VI-X) G-9/3', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-II', 'UC' => 'UC-34 Sector G-9/1 G-9/3 G-9/4'],
            ['emis' => 251, 'name' => 'IMSG(VI-X) G-9/4', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-II', 'UC' => 'UC-34 Sector G-9/1 G-9/3 G-9/4'],
            ['emis' => 252, 'name' => 'IMS(I-V) No.2  G-9/4', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-34 Sector G-9/1 G-9/3 G-9/4'],
            ['emis' => 253, 'name' => 'IMS(I-V) No.1  G-9/4', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-34 Sector G-9/1 G-9/3 G-9/4'],
            ['emis' => 254, 'name' => 'IMS(I-V) No.3 St 68  G-9/3', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-34 Sector G-9/1 G-9/3 G-9/4'],
            ['emis' => 255, 'name' => 'IMS(I-V) No.2 St 7  G-9/3', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-34 Sector G-9/1 G-9/3 G-9/4'],
            ['emis' => 256, 'name' => 'IMS(I-V) No.1  G-9/3', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-34 Sector G-9/1 G-9/3 G-9/4'],
            ['emis' => 257, 'name' => 'IMCG G-9/2', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'Urban-II', 'UC' => 'UC-35 Sector G-9/2'],
            ['emis' => 258, 'name' => 'IMSG(I-X) G-9/1', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Urban-II', 'UC' => 'UC-34 Sector G-9/1 G-9/3 G-9/4'],
            ['emis' => 259, 'name' => 'IMS(I-V) No.1  G-9/2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-35 Sector G-9/2'],
            ['emis' => 260, 'name' => 'IMS(I-V) No.2 G-9/2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-35 Sector G-9/2'],
            ['emis' => 261, 'name' => 'IMS(I-V) No.3  G-9/2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-35 Sector G-9/2'],
            ['emis' => 262, 'name' => 'IMS(I-V) No.4  G-9/2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-35 Sector G-9/2'],
            ['emis' => 263, 'name' => 'IMS(I-V)  G-9/1', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-34 Sector G-9/1 G-9/3 G-9/4'],
            ['emis' => 264, 'name' => 'IMS(I-V)  F-10/1', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-29 Sector F-10 F-11'],
            ['emis' => 265, 'name' => 'IMS(I-V)  F-10/2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-29 Sector F-10 F-11'],
            ['emis' => 266, 'name' => 'IMS(I-V)  F-10/4', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-29 Sector F-10 F-11'],
            ['emis' => 267, 'name' => 'IMSG(VI-X) G-10/1', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-II', 'UC' => 'UC-37 Sector G-10/1 G-10/2'],
            ['emis' => 268, 'name' => 'IMSG(I-X) G-10/3', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Urban-II', 'UC' => 'UC-36 Sector G-10/3 G-10/4'],
            ['emis' => 269, 'name' => 'IMS(I-V)  G-10/3', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-36 Sector G-10/3 G-10/4'],
            ['emis' => 270, 'name' => 'IMS(I-V)  G-10/4', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-36 Sector G-10/3 G-10/4'],
            ['emis' => 271, 'name' => 'IMS(I-V)  G-10/1', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-37 Sector G-10/1 G-10/2'],
            ['emis' => 272, 'name' => 'IMS(I-V) No.1 G-10/2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-37 Sector G-10/1 G-10/2'],
            ['emis' => 273, 'name' => 'IMS(I-V) No.2 G-10/2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-37 Sector G-10/1 G-10/2'],
            ['emis' => 274, 'name' => 'IMS(I-V) G-11/1', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-38 Sector G-11'],
            ['emis' => 275, 'name' => 'IMSG(I-X) G-11/2', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Urban-II', 'UC' => 'UC-38 Sector G-11'],
            ['emis' => 276, 'name' => 'IMSG(VI-X) F-11/1', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-II', 'UC' => 'UC-29 Sector F-10 F-11'],
            ['emis' => 277, 'name' => 'IMS(I-V)  G-11/2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-38 Sector G-11'],
            ['emis' => 278, 'name' => 'IMSG(VI-X) G-11/1', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-II', 'UC' => 'UC-38 Sector G-11'],
            ['emis' => 279, 'name' => 'IMSG(VI-X) I-8/1', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-II', 'UC' => 'UC-40 I-8 & H8'],
            ['emis' => 280, 'name' => 'IMS(I-V) I-8/1', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-40 I-8 & H8'],
            ['emis' => 281, 'name' => 'IMSG (I-VIII) I-9/4', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Urban-II', 'UC' => 'UC-41 I-9 & H9'],
            ['emis' => 282, 'name' => 'IMS(I-V) No.1  I-9/4', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-41 I-9 & H9'],
            ['emis' => 283, 'name' => 'IMS(I-V) No.2  I-9/4', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-41 I-9 & H9'],
            ['emis' => 284, 'name' => 'IMSG (I-VIII) I-8/1', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Urban-II', 'UC' => 'UC-40 I-8 & H8'],
            ['emis' => 285, 'name' => 'IMS(I-V) AIOU Colony', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-42 Sector I-10 & H-10'],
            ['emis' => 286, 'name' => 'IMCG I-9/1', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'Urban-II', 'UC' => 'UC-41 I-9 & H9'],
            ['emis' => 287, 'name' => 'IMSG(VI-X) I-10/4', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-II', 'UC' => 'UC-42 Sector I-10 & H-10'],
            ['emis' => 288, 'name' => 'IMSG (I-VIII) I-10/4', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Urban-II', 'UC' => 'UC-42 Sector I-10 & H-10'],
            ['emis' => 289, 'name' => 'IMS(I-V) No.1  I-10/1', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-42 Sector I-10 & H-10'],
            ['emis' => 290, 'name' => 'IMS(I-V) No.2  I-10/1', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-42 Sector I-10 & H-10'],
            ['emis' => 291, 'name' => 'IMS (I-V) I-10/2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-42 Sector I-10 & H-10'],
            ['emis' => 292, 'name' => 'IMS(I-V) No.2  I-9/1', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-41 I-9 & H9'],
            ['emis' => 293, 'name' => 'IMSG(VI-X) I-9/4', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Urban-II', 'UC' => 'UC-41 I-9 & H9'],
            ['emis' => 294, 'name' => 'IMS(I-V) No.1 I-9/1', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-II', 'UC' => 'UC-41 I-9 & H9'],
            ['emis' => 295, 'name' => 'IMS(I-V) No.2 G-7/2', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-31 Sector G-7/1 G-7/2'],
            ['emis' => 296, 'name' => 'IMCB G-9/4', 'gender' => 'boys', 'type' => 'VI-XII', 'sector' => 'Urban-II', 'UC' => 'UC-35 Sector G-9/2'],
            ['emis' => 297, 'name' => 'IMSB(VI-X) G-8/1', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Urban-I', 'UC' => 'UC-33 Sector G-8/1 G-8/2'],
            ['emis' => 298, 'name' => 'IMSB(VI-X) G-10/3', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Urban-II', 'UC' => 'UC-36 Sector G-10/3 G-10/4'],
            ['emis' => 299, 'name' => 'IMSB(VI-X),G-9/1', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Urban-II', 'UC' => 'UC-34 Sector G-9/1 G-9/3 G-9/4'],
            ['emis' => 300, 'name' => 'IMS(I-V) F-8/3', 'gender' => 'co-edu', 'type' => 'I-V', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 301, 'name' => 'IMSB (VI-X) F-8/3', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 302, 'name' => 'IMSB(VI-X) G-11/2', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Urban-II', 'UC' => 'UC-38 Sector G-11'],
            ['emis' => 303, 'name' => 'IMSB(VI-X) G-7/3-1', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Urban-I', 'UC' => 'UC-30 Sector G-7/3 G-7/4'],
            ['emis' => 304, 'name' => 'IMSB(VI-X) G-6/4', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Urban-I', 'UC' => 'UC-27 Sector G-6/2'],
            ['emis' => 305, 'name' => 'IMCB G-6/2', 'gender' => 'boys', 'type' => 'VI-XII', 'sector' => 'Urban-I', 'UC' => 'UC-27 Sector G-6/2'],
            ['emis' => 306, 'name' => 'IMSB (VI-X) F-6/2', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Urban-I', 'UC' => 'UC-25 Sector F-6'],
            ['emis' => 307, 'name' => 'IMCB G-7/2', 'gender' => 'boys', 'type' => 'VI-XII', 'sector' => 'Urban-I', 'UC' => 'UC-31 Sector G-7/1 G-7/2'],
            ['emis' => 308, 'name' => 'IMCB G-7/4', 'gender' => 'boys', 'type' => 'VI-XII', 'sector' => 'Urban-I', 'UC' => 'UC-30 Sector G-7/3 G-7/4'],
            ['emis' => 309, 'name' => 'IMSB(VI-X) No.1 I-9/4', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Urban-II', 'UC' => 'UC-41 I-9 & H9'],
            ['emis' => 310, 'name' => 'IMCB I-10/1,Street No.17', 'gender' => 'boys', 'type' => 'VI-XII', 'sector' => 'Urban-II', 'UC' => 'UC-42 Sector I-10 & H-10'],
            ['emis' => 311, 'name' => 'IMSB(VI-X) No.2 I-9/4', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Urban-II', 'UC' => 'UC-41 I-9 & H9'],
            ['emis' => 312, 'name' => 'IMSB(VI-X) I-10/2', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Urban-II', 'UC' => 'UC-42 Sector I-10 & H-10'],
            ['emis' => 313, 'name' => 'IMSB (I-VIII) I-8/1', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Urban-II', 'UC' => 'UC-40 I-8 & H8'],
            ['emis' => 314, 'name' => 'IMSB (VI-X) I-8/4', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Urban-II', 'UC' => 'UC-40 I-8 & H8'],
            ['emis' => 315, 'name' => 'IMSB(VI-X) G-8/4', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Urban-I', 'UC' => 'UC-32 Sector G-8/3 G-8/4'],
            ['emis' => 316, 'name' => 'IMSB(VI-VIII Technical) G-7/4', 'gender' => 'boys', 'type' => 'VI-VIII', 'sector' => 'Urban-I', 'UC' => 'UC-30 Sector G-7/3 G-7/4'],
            ['emis' => 317, 'name' => 'IMSB(VI-X) E-9', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 401, 'name' => 'IMCB (VI-XII), (BSK) BHARA KAU', 'gender' => 'boys', 'type' => 'VI-XII', 'sector' => 'B.K', 'UC' => 'UC-04 Kot Hathial (Shamal) Bharakahu'],
            ['emis' => 402, 'name' => 'IMCB (VI-XII), CHAKSHAHZAD', 'gender' => 'boys', 'type' => 'VI-XII', 'sector' => 'B.K', 'UC' => 'UC-22 Chak Shehzad'],
            ['emis' => 403, 'name' => 'IMSB (I-X) BHARA KAU', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-04 Kot Hathial (Shamal) Bharakahu'],
            ['emis' => 404, 'name' => 'IMSB (I-X) CHATTAR', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 405, 'name' => 'IMSB (VI-X) KUREE', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'B.K', 'UC' => 'UC-23 Kuri (Banigala & Mohra Noor)'],
            ['emis' => 406, 'name' => 'IMSB (vi-x) Noor pur Shahan', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'B.K', 'UC' => 'UC-02 Noorpur Shahan (Barriamam)'],
            ['emis' => 407, 'name' => 'IMCB (VI-XII) PIND BEGWAL', 'gender' => 'boys', 'type' => 'VI-XII', 'sector' => 'B.K', 'UC' => 'UC-07 Pind Begwal'],
            ['emis' => 408, 'name' => 'IMSB (I-X) SHAHDARA', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 409, 'name' => 'IMSB (VI-X) RAWAL DAM', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'B.K', 'UC' => 'UC-24 Rawal Margala town'],
            ['emis' => 410, 'name' => 'IMSB (VI-X) TALHAR', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 411, 'name' => 'IMSB (I-X), SAID PUR', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-01 Saidpur'],
            ['emis' => 412, 'name' => 'IMSB (I-VIII), BOBRI', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'B.K', 'UC' => 'UC-04 Kot Hathial (Shamal) Bharakahu'],
            ['emis' => 413, 'name' => 'IMSB (I-VIII) JANDALA (F.A)', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 414, 'name' => 'IMSB (I-X), MAIRA BEGWAL', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-07 Pind Begwal'],
            ['emis' => 415, 'name' => 'IMSB (I-VIII), MOHRA NOOR NIH', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'B.K', 'UC' => 'UC-23 Kuri (Banigala & Mohra Noor)'],
            ['emis' => 416, 'name' => 'IMSB (I-X) PHULGRAN F.A', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-06 Phulgran'],
            ['emis' => 417, 'name' => 'IMSB (I-VIII), KOT HATHIAL (NAI ABADI)', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'B.K', 'UC' => 'UC-04 Kot Hathial (Shamal) Bharakahu'],
            ['emis' => 418, 'name' => 'IMSB (I-VIII), MALWAR', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 419, 'name' => 'IMSB (I-VIII), SATRA MEEL', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'B.K', 'UC' => 'UC-46 Badhana Kalan'],
            ['emis' => 420, 'name' => 'IMSB (I-V), ATHAL', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 421, 'name' => 'IMSB (I-V), BHUDDO', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 422, 'name' => 'IMSB (I-V), CHAHANN MASTAL (F.A) H-11', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-43 Sector I-11 & H-11'],
            ['emis' => 423, 'name' => 'IMSB (I-V), DHOKE JERRANI', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 424, 'name' => 'IMSB (I-V), DHOKE SYEDAN', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 425, 'name' => 'IMSB (I-V), DOHALA SYEDAN', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-01 Saidpur'],
            ['emis' => 426, 'name' => 'IMSB (I-V), KALRAN', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 427, 'name' => 'IMSB (I-V), MALOT', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-06 Phulgran'],
            ['emis' => 428, 'name' => 'IMSB(I-V), MANGIAL(F.A),', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 429, 'name' => 'IMSB (I-V), MAL', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 430, 'name' => 'IMSB (I-V), NOOR PUR SHAHAN', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-02 Noorpur Shahan (Barriamam)'],
            ['emis' => 431, 'name' => 'IMSB (I-V), PALALI', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 432, 'name' => 'IMSB (I-V), PIND BEGWAL', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-07 Pind Begwal'],
            ['emis' => 433, 'name' => 'IMSB (I-V), RUMLI', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-24 Rawal Margala town'],
            ['emis' => 434, 'name' => 'IMSB (I-V), SIHALI', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 435, 'name' => 'IMSB (I-V), TALHAR (FA) IBD', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 436, 'name' => 'IMSB (I-V), KOT HATHIAL, QAZIABAD', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-04 Kot Hathial (Shamal) Bharakahu'],
            ['emis' => 437, 'name' => 'IMSB (I-V), GOKINA', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 438, 'name' => 'IMSB (I-V), KUREE', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-23 Kuri (Banigala & Mohra Noor)'],
            ['emis' => 439, 'name' => 'IMSB (I-VIII), MALPUR', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'B.K', 'UC' => 'UC-03 Malpur'],
            ['emis' => 440, 'name' => 'IMSB (I-V), RAWAL DAM,', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-24 Rawal Margala town'],
            ['emis' => 441, 'name' => 'IMSB (I-VIII), CHATTA BAKHTAWAR', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 442, 'name' => 'IMCG (I-XII), MARGALLA TOWN', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'B.K', 'UC' => 'UC-39 Maira Sumbal Jaffar (G-12, G-13)'],
            ['emis' => 443, 'name' => 'IMCG (VI-XII),KOT HATHIAL BHARA KAHU', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'B.K', 'UC' => 'UC-04 Kot Hathial (Shamal) Bharakahu'],
            ['emis' => 444, 'name' => 'IMCG (I-XII), UNIVERSITY COLONY (U.C)', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'B.K', 'UC' => 'UC-22 Chak Shehzad'],
            ['emis' => 445, 'name' => 'IMSG (I-X), NHC', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-22 Chak Shehzad'],
            ['emis' => 446, 'name' => 'IMCG (VI-XII) NHC, CHAK SHAHZAD', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'B.K', 'UC' => 'UC-22 Chak Shehzad'],
            ['emis' => 447, 'name' => 'IMSG (I-X) GOKINA', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 448, 'name' => 'IMSG (I-X) KURRI', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-23 Kuri (Banigala & Mohra Noor)'],
            ['emis' => 449, 'name' => 'IMCG (VI-XII) MALPUR', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'B.K', 'UC' => 'UC-03 Malpur'],
            ['emis' => 450, 'name' => 'IMSG (I-X) PHULGRAN', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-06 Phulgran'],
            ['emis' => 451, 'name' => 'IMCG,  RAWAL TOWN', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'B.K', 'UC' => 'UC-24 Rawal Margala town'],
            ['emis' => 452, 'name' => 'IMSG (I-X) TALHAR', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 453, 'name' => 'IMCG (I-XII) MAIRA BEGWAL', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'B.K', 'UC' => 'UC-07 Pind Begwal'],
            ['emis' => 454, 'name' => 'IMSG (I-X) LAKHWAL', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 455, 'name' => 'IMCG (I-XII) PIND BEGWAL', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'B.K', 'UC' => 'UC-07 Pind Begwal'],
            ['emis' => 456, 'name' => 'IMSG (I-X) NOORPUR SHAHAN', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-02 Noorpur Shahan (Barriamam)'],
            ['emis' => 457, 'name' => 'IMSG (I-X) SHAHDRA KHURD', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 458, 'name' => 'IMSG (I-X), SAID PUR', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-01 Saidpur'],
            ['emis' => 459, 'name' => 'IMSG (I-X), MALOT', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-06 Phulgran'],
            ['emis' => 460, 'name' => 'IMSG (I-VIII), SHAHDRA KALAN', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 461, 'name' => 'IMSG (I-VIII), BAIN NALA', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'B.K', 'UC' => 'UC-01 Saidpur'],
            ['emis' => 462, 'name' => 'IMSG (I-VIII) Mandla (FA)', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 463, 'name' => 'IMSG (I-X), MOHRA NOOR', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'B.K', 'UC' => 'UC-23 Kuri (Banigala & Mohra Noor)'],
            ['emis' => 464, 'name' => 'IMSG (I-VIII), BHARA KAU', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'B.K', 'UC' => 'UC-04 Kot Hathial (Shamal) Bharakahu'],
            ['emis' => 465, 'name' => 'IMSG (I-VIII), BOBRI', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'B.K', 'UC' => 'UC-04 Kot Hathial (Shamal) Bharakahu'],
            ['emis' => 466, 'name' => 'IMSG (I-VIII), KOT HATHIAL', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'B.K', 'UC' => 'UC-04 Kot Hathial (Shamal) Bharakahu'],
            ['emis' => 467, 'name' => 'IMSG (I-VIII), SANJALIAN', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 468, 'name' => 'IMSG (I-V), ATHAL', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 469, 'name' => 'IMSG (I-V), (NHC) CHAK SHEHZAD', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-22 Chak Shehzad'],
            ['emis' => 470, 'name' => 'IMSG (I-V), DHOKE JERRANI', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 471, 'name' => 'IMSG (I-V), KOT HATHIAL, NAI ABADI', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-04 Kot Hathial (Shamal) Bharakahu'],
            ['emis' => 472, 'name' => 'IMSG (I-VIII), MOHRIAN', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 473, 'name' => 'IMSG (I-V), PIND BEGWAL, DANA', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-07 Pind Begwal'],
            ['emis' => 474, 'name' => 'IMSG (I-V), SHAH PUR', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 475, 'name' => 'IMSG (I-V), SUBBAN', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 476, 'name' => 'IMSG (I-V) , SHAHZAD TOWN', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-22 Chak Shehzad'],
            ['emis' => 477, 'name' => 'IMSG (I-V), BHARA KAU, NAI ABADI', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-04 Kot Hathial (Shamal) Bharakahu'],
            ['emis' => 478, 'name' => 'IMSG (I-V), MALPUR (F.A)', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-03 Malpur'],
            ['emis' => 479, 'name' => 'IMSG (I-V) Maira Malpur', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'B.K', 'UC' => 'UC-03 Malpur'],
            ['emis' => 501, 'name' => 'IMCG Herdogher', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 502, 'name' => 'IMCG. Rawat', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'Sihala', 'UC' => 'UC-12 Rawat'],
            ['emis' => 503, 'name' => 'IMCG Humak', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'Sihala', 'UC' => 'UC-13 Humak'],
            ['emis' => 504, 'name' => 'IMSG (VI-X) Sihala', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 505, 'name' => 'IMSG (I-X) Nara Syedan', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 506, 'name' => 'IMSG (I-X) Dhoke Gangal', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 507, 'name' => 'IMCG (I-X) Pind Malkan', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala', 'UC' => 'UC-17 Koral'],
            ['emis' => 508, 'name' => 'IMCG Lohi Bher', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Sihala', 'UC' => 'UC-15 Lohi Bhar'],
            ['emis' => 509, 'name' => 'IMCG  Mohra Nagial', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 510, 'name' => 'IMSG (I-X)  Humak', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala', 'UC' => 'UC-13 Humak'],
            ['emis' => 511, 'name' => 'IMSG (I-X) Gagri', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala', 'UC' => 'UC-13 Humak'],
            ['emis' => 512, 'name' => 'IMSG (I-X) Upran Gohra', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 513, 'name' => 'IMSG (I-VIII) Bhimber Trar', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 514, 'name' => 'IMSG (I-VIII) Mohri Rawat', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala', 'UC' => 'UC-12 Rawat'],
            ['emis' => 515, 'name' => 'IMSG (I-X) R/Col. Rawat', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala', 'UC' => 'UC-12 Rawat'],
            ['emis' => 516, 'name' => 'IMSG (I-VIII) Bhangril', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 517, 'name' => 'IMSG (I-VIII) Rajwal', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 518, 'name' => 'IMSG (I-X) Dhaliala', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 519, 'name' => 'IMSG (I-VIII) Niazian', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 520, 'name' => 'IMSG (I-V) (M.T)  Humak', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-13 Humak'],
            ['emis' => 521, 'name' => 'IMSG (I-VIII)Peija', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 522, 'name' => 'IMSG (I-V) Pindory Syedan', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 523, 'name' => 'IMSG (I-VIII) Miana Thub', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 524, 'name' => 'IMSG (I-VIII) Jandala', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 525, 'name' => 'IMSG (I-V)  Rawat', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-12 Rawat'],
            ['emis' => 526, 'name' => 'IMSG (I-V) Sheikhpur', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 527, 'name' => 'IMSG (I-V) Herdogher', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 528, 'name' => 'IMSG (I-V) Mughal', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-11 Mughal'],
            ['emis' => 529, 'name' => 'IMSG (I-V) Sihala', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 530, 'name' => 'IMSG (I-V) Sihala Mirzian', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 531, 'name' => 'IMSG (I-V) Hoon Dhamial', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-16 Darwala'],
            ['emis' => 532, 'name' => 'IMSG (I-V) Gohra Mast', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 533, 'name' => 'IMSG (I-V) Ladhiot', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 534, 'name' => 'IMSG (I-V) Humak', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-13 Humak'],
            ['emis' => 535, 'name' => 'IMSG (I-V) GANGOTA SYEDAN', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 536, 'name' => 'IMSG (I-V)Boora Bangial', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 537, 'name' => 'IMSG (I-V) Mohri Mughal', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-11 Mughal'],
            ['emis' => 538, 'name' => 'IMSG (I-VIII)  PTC Sihala', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 539, 'name' => 'IMSG (I-V)  PWD Col', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 540, 'name' => 'IMSG (I-V) Sihala Khurd', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 541, 'name' => 'IMCB  Mughal', 'gender' => 'boys', 'type' => 'VI-XII', 'sector' => 'Sihala', 'UC' => 'UC-11 Mughal'],
            ['emis' => 542, 'name' => 'IMSB (VI-X) Sihala', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 543, 'name' => 'IMCB Rawat (F.A)', 'gender' => 'boys', 'type' => 'VI-XII', 'sector' => 'Sihala', 'UC' => 'UC-12 Rawat'],
            ['emis' => 544, 'name' => 'IMCB  Bhimber Trar', 'gender' => 'boys', 'type' => 'VI-XII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 545, 'name' => 'IMCB Humak', 'gender' => 'boys', 'type' => 'VI-XII', 'sector' => 'Sihala', 'UC' => 'UC-13 Humak'],
            ['emis' => 546, 'name' => 'IMCB Pahg Panwal', 'gender' => 'boys', 'type' => 'VI-XII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 547, 'name' => 'IMCB  Mohra Nagial', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 548, 'name' => 'IMSB (I-X) Gagri', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Sihala', 'UC' => 'UC-13 Humak'],
            ['emis' => 549, 'name' => 'IMSB (I-X) Dhaliala', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 550, 'name' => 'IMSB (I-X) Banni Saran', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 551, 'name' => 'IMSB (I-V) Sihala', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 552, 'name' => 'IMSB (I-V) Lohi Bher', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-15 Lohi Bhar'],
            ['emis' => 553, 'name' => 'IMSB (I-V) Bhimber Trar', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 554, 'name' => 'IMSB (I-VIII) Ara Burji', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Sihala', 'UC' => 'UC-16 Darwala'],
            ['emis' => 555, 'name' => 'IMSB (I-V) Humak', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-13 Humak'],
            ['emis' => 556, 'name' => 'IMSB (I-VIII)S/Mirzian', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 557, 'name' => 'IMSB (I-V) Mughal', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-11 Mughal'],
            ['emis' => 558, 'name' => 'IMSB (I-VIII) Herdogher', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 559, 'name' => 'IMSB (I-V) Darwala', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-16 Darwala'],
            ['emis' => 560, 'name' => 'IMSB (I-V) Boora Bangial', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 561, 'name' => 'IMSB (I-V) Pind  Malkan', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-17 Koral'],
            ['emis' => 562, 'name' => 'IMSB (I-V) Mohra Kalu', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 563, 'name' => 'IMSB (I-V) D/Mai Nawab', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-16 Darwala'],
            ['emis' => 564, 'name' => 'IMSB (I-V) Rajwal', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 565, 'name' => 'IMSB (I-V) Kortana', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 566, 'name' => 'IMSB (I-V) Bhangril', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 567, 'name' => 'IMSB (I-V) Chak', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 568, 'name' => 'IMSB (I-V) Mohri Rawat', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-12 Rawat'],
            ['emis' => 569, 'name' => 'IMSB (I-VIII), Koral', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Sihala', 'UC' => 'UC-17 Koral'],
            ['emis' => 570, 'name' => 'IMSB (I-VIII) Nara Syedan', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 571, 'name' => 'IMSB (I-V)Chak Kamdar', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 572, 'name' => 'IMSB (I-V). Sigga', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 573, 'name' => 'IMSG (I-V) CBR Colony', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-15 Lohi Bhar'],
            ['emis' => 574, 'name' => 'IMS (I-V) Soan Garden, Lohi Bheer', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-15 Lohi Bhar'],
            ['emis' => 575, 'name' => 'IMS (I-V) Gohra Shahan', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 601, 'name' => 'IMCB (VI-XII) Tarnol', 'gender' => 'boys', 'type' => 'VI-XII', 'sector' => 'Tarnol', 'UC' => 'UC-47 Tarnol'],
            ['emis' => 602, 'name' => 'IMSB (VI-X) Sang Jani', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 603, 'name' => 'IMSB (I-X) Naugazi', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Tarnol', 'UC' => 'UC-43 Sector I-11 & H-11'],
            ['emis' => 604, 'name' => 'IMSB (I-X) I-14', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Tarnol', 'UC' => 'UC-44 Bokra (I-12. H-11 & H-13)'],
            ['emis' => 605, 'name' => 'IMSB (VI-X) Noon', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 606, 'name' => 'IMSB (I-X) Maira Akku', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 607, 'name' => 'IMSB (VI-X) Shah Allah Ditta', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Tarnol', 'UC' => 'UC-49 Shah Allah Ditta'],
            ['emis' => 608, 'name' => 'IMSB (VI-X) Golra', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Tarnol', 'UC' => 'UC-50 Golra Sharif'],
            ['emis' => 609, 'name' => 'IMSB (I-X) Badana Kalan', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Tarnol', 'UC' => 'UC-46 Badhana Kalan'],
            ['emis' => 610, 'name' => 'IMSG (I-X) Sangjani', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 611, 'name' => 'IMSG (I-X) Jhangi Syedan (F.A.)', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 612, 'name' => 'IMCG (I-XII) Shah Allah Ditta', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Tarnol', 'UC' => 'UC-49 Shah Allah Ditta'],
            ['emis' => 613, 'name' => 'IMCG (I-XII) Badana Kalan', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Tarnol', 'UC' => 'UC-46 Badhana Kalan'],
            ['emis' => 614, 'name' => 'IMCG (I-XII) Tarnaul', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Tarnol', 'UC' => 'UC-47 Tarnol'],
            ['emis' => 615, 'name' => 'IMCG (I-XII) Golra', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Tarnol', 'UC' => 'UC-50 Golra Sharif'],
            ['emis' => 616, 'name' => 'IMSG (VI-X) I-14/3', 'gender' => 'girls', 'type' => 'VI-X', 'sector' => 'Tarnol', 'UC' => 'UC-44 Bokra (I-12. H-11 & H-13)'],
            ['emis' => 617, 'name' => 'IMSG (I-X) Naugazi (F.A)', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Tarnol', 'UC' => 'UC-43 Sector I-11 & H-11'],
            ['emis' => 618, 'name' => 'IMSG (I-X) BQB', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Tarnol', 'UC' => 'UC-43 Sector I-11 & H-11'],
            ['emis' => 619, 'name' => 'IMSB (I-VIII) Dhoke Jouri', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 620, 'name' => 'IMSB (I-VIII) Dhoke Paracha', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 621, 'name' => 'IMSB (I-X) Maira Beri(F.A)', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 622, 'name' => 'IMSB (I-VIII) Chellow', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Tarnol', 'UC' => 'UC-50 Golra Sharif'],
            ['emis' => 623, 'name' => 'IMSG (I-VIII) Dhoke Jouri', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 624, 'name' => 'IMSG (I-VIII) Pind Paracha', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 625, 'name' => 'IMSG (I-VIII) Noon', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 626, 'name' => 'IMSG (I-VIII) Dhreak Mohri', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 627, 'name' => 'IMSG (I-X) Maira Beri', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 628, 'name' => 'IMSG (I-VIII) Dhoke Paracha', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 629, 'name' => 'IMSG (I-VIII) Sarae Kharboza (F.A)', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Tarnol', 'UC' => 'UC-48 Sarai Kharbuza'],
            ['emis' => 630, 'name' => 'IMSB (I-V) Tarnaul', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-47 Tarnol'],
            ['emis' => 631, 'name' => 'IMSB (I-V) Tamman', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-47 Tarnol'],
            ['emis' => 632, 'name' => 'IMSB (I-V) Sang Jani', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 633, 'name' => 'IMSB (I-V) Dora', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-47 Tarnol'],
            ['emis' => 634, 'name' => 'IMSB (I-V) Sheikhpur', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-47 Tarnol'],
            ['emis' => 635, 'name' => 'IMSB (I-V) Pind Hoon', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-47 Tarnol'],
            ['emis' => 636, 'name' => 'IMSB (I-V) Noon', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 637, 'name' => 'IMSB (I-V) Shah Allah Ditta', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-49 Shah Allah Ditta'],
            ['emis' => 638, 'name' => 'IMSB (I-V) Karamabad', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-50 Golra Sharif'],
            ['emis' => 639, 'name' => 'IMSB (I-V) Dhoke Lubana', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-50 Golra Sharif'],
            ['emis' => 640, 'name' => 'IMSB (I-V) JOHD', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-43 Sector I-11 & H-11'],
            ['emis' => 641, 'name' => 'IMSB (I-V) Sarae Karboza', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-48 Sarai Kharbuza'],
            ['emis' => 642, 'name' => 'IMSB (I-V) Pind Parian', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-48 Sarai Kharbuza'],
            ['emis' => 643, 'name' => 'IMSB (I-V) Dhreak Mohri', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 644, 'name' => 'IMSB (I-V) Seri Saral', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 645, 'name' => 'IMSB (I-V) Bokra', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-44 Bokra (I-12. H-11 & H-13)'],
            ['emis' => 646, 'name' => 'IMSB (I-V) Jhangi Syedan (FA)', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 647, 'name' => 'IMSB (I-V) Golra', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-50 Golra Sharif'],
            ['emis' => 648, 'name' => 'IMSG (I-V) Bheka Syedan', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 649, 'name' => 'IMSG (I-V) Pind Parian', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-48 Sarai Kharbuza'],
            ['emis' => 650, 'name' => 'IMSG (I-V) Sheikhpur', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-47 Tarnol'],
            ['emis' => 651, 'name' => 'IMSG (I-V) Dhoke Hashoo', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-49 Shah Allah Ditta'],
            ['emis' => 652, 'name' => 'IMSG (I-V) Dhoke Suleman', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-49 Shah Allah Ditta'],
            ['emis' => 653, 'name' => 'IMSG (I-V) Sarae Madhu', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-49 Shah Allah Ditta'],
            ['emis' => 654, 'name' => 'IMSG (I-V) I-14/3', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Tarnol', 'UC' => 'UC-44 Bokra (I-12. H-11 & H-13)'],
            ['emis' => 655, 'name' => 'IMS (I-VIII) D-17', 'gender' => 'co-edu', 'type' => 'I-VIII', 'sector' => 'Tarnol', 'UC' => 'UC-39 Maira Sumbal Jaffar (G-12, G-13)'],
            ['emis' => 701, 'name' => 'IMCB,NILORE', 'gender' => 'boys', 'type' => 'VI-XII', 'sector' => 'Nilore', 'UC' => 'UC-18 Khana Dak'],
            ['emis' => 702, 'name' => 'IMSB(VI-X) CHIRAH', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Nilore', 'UC' => 'UC-09 Charah'],
            ['emis' => 703, 'name' => 'IMSB(I-X) TUMAIR', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Nilore', 'UC' => 'UC-08 Tumair'],
            ['emis' => 704, 'name' => 'IMSB(I-X)JAGIOT', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Nilore', 'UC' => 'UC-08 Tumair'],
            ['emis' => 705, 'name' => 'IMSB(VI-X)JHANG SYDEN', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Nilore', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 706, 'name' => 'IMSB(VI-X)TARLAI', 'gender' => 'boys', 'type' => 'VI-X', 'sector' => 'Nilore', 'UC' => 'UC-19 Tarlai Kalan'],
            ['emis' => 707, 'name' => 'IMSB(I-X) KHANNA DAK', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Nilore', 'UC' => 'UC-18 Khana Dak'],
            ['emis' => 708, 'name' => 'IMCB,JABA TALI', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Nilore', 'UC' => 'UC-20 Alipur'],
            ['emis' => 709, 'name' => 'IMSB(I-X)KIRPA', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Nilore', 'UC' => 'UC-10 Kirpa'],
            ['emis' => 710, 'name' => 'IMCG,NILORE', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'Nilore', 'UC' => 'UC-18 Khana Dak'],
            ['emis' => 711, 'name' => 'IMCG CHIRAH', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'Nilore', 'UC' => 'UC-09 Charah'],
            ['emis' => 712, 'name' => 'IMCG,PUNJGRAN', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'Nilore', 'UC' => 'UC-23 Alipur'],
            ['emis' => 713, 'name' => 'IMCG,TARLAI', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'Nilore', 'UC' => 'UC-19 Tarlai Kalan'],
            ['emis' => 714, 'name' => 'IMCG,JAGIOT', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Nilore', 'UC' => 'UC-08 Tumair'],
            ['emis' => 715, 'name' => 'IMCG,PEHOUNT', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Nilore', 'UC' => 'UC-21 Sohan'],
            ['emis' => 716, 'name' => 'IMCG,THANDA PANI (FA)', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Nilore', 'UC' => 'UC-20 Alipur'],
            ['emis' => 717, 'name' => 'IMSB(I-X) KHANNA NAI ABADI', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Nilore', 'UC' => 'UC-18 Khana Dak'],
            ['emis' => 718, 'name' => 'IMSB(I-VIII) ALI PUR', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Nilore', 'UC' => 'UC-20 Alipur'],
            ['emis' => 719, 'name' => 'IMSB(I-VIII) DELLA', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Nilore', 'UC' => 'UC-20 Alipur'],
            ['emis' => 720, 'name' => 'IMSB(I-X) THANDA PANI', 'gender' => 'boys', 'type' => 'I-X', 'sector' => 'Nilore', 'UC' => 'UC-20 Alipur'],
            ['emis' => 721, 'name' => 'IMSB(I-VIII) PEHOUNT', 'gender' => 'boys', 'type' => 'I-VIII', 'sector' => 'Nilore', 'UC' => 'UC-21 Sohan'],
            ['emis' => 722, 'name' => 'IMSG(I-VIII) KH. DAK', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Nilore', 'UC' => 'UC-18 Khana Dak'],
            ['emis' => 723, 'name' => 'IMSG(I-X) NEW SHAKRIAL', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Nilore', 'UC' => 'UC-21 New Shakrial'],
            ['emis' => 724, 'name' => 'IMSG (I-VIII) KALIA (FA)', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Nilore', 'UC' => 'UC-24 Chirrah'],
            ['emis' => 725, 'name' => 'IMSG(I-X) JABA TAILI', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Nilore', 'UC' => 'UC-20 Alipur'],
            ['emis' => 726, 'name' => 'IMSB(I-V)SOHAN', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-21 Sohan'],
            ['emis' => 727, 'name' => 'IMSB(I-V)SHARIFABAD', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-47 Tarlai'],
            ['emis' => 728, 'name' => 'IMSB(I-V)KHADRAPPAR', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-47 Tarlai'],
            ['emis' => 729, 'name' => 'IMSB(I-V) CH. BANGIAL', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-25 Kirpa'],
            ['emis' => 730, 'name' => 'IMSB(I-V)CHIRAH', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-09 Charah'],
            ['emis' => 731, 'name' => 'IMSB(I-VIII) KIJNAH', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-21 Tumair'],
            ['emis' => 732, 'name' => 'IMSB(I-V) MOHARA SOLINA', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-24 Chirrah'],
            ['emis' => 733, 'name' => 'IMSB(I-V) JHANG SYDEN', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 734, 'name' => 'IMSB(I-V)TARLAI', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-19 Tarlai Kalan'],
            ['emis' => 735, 'name' => 'IMSB(I-V)MOHARA', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-21 Tumair'],
            ['emis' => 736, 'name' => 'IMSB(I-V)ARA', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-25 Kirpa'],
            ['emis' => 737, 'name' => 'IMSB(I-V)KHANNA KAK', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-Dhoke Kala Khan RWP'],
            ['emis' => 738, 'name' => 'IMSB(I-V)PINDMISTRIAN', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-22 Thanda Pani'],
            ['emis' => 739, 'name' => 'IMSG(I-V)SHAKRIAL', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-Khana Dak II RWP'],
            ['emis' => 740, 'name' => 'IMSG(I-V) KHANNA NAI ABADI', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-18 Khana Dak'],
            ['emis' => 741, 'name' => 'IMSG(I-V) NO.I TARLAI', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-19 Tarlai Kalan'],
            ['emis' => 742, 'name' => 'IMSG(I-V) NO.2 TARLAI', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-19 Tarlai Kalan'],
            ['emis' => 743, 'name' => 'IMSG(I-V)TAMMA', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-47 Tarlai'],
            ['emis' => 744, 'name' => 'IMSG(I-V) ALI PUR (MV)', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-20 Alipur'],
            ['emis' => 745, 'name' => 'IMSG(I-V)ALI PUR FRASH', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-20 Alipur'],
            ['emis' => 746, 'name' => 'IMSG(I-V) SEVERA', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-20 Pind Begwal'],
            ['emis' => 747, 'name' => 'IMSG (I-V) CHOUNIAL BANGIAL', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-25 Kirpa'],
            ['emis' => 748, 'name' => 'IMSG(I-V)HERNO', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-22 Thanda Pani'],
            ['emis' => 749, 'name' => 'IMSG(I-X) DARKALA', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Nilore', 'UC' => 'UC-22 Thanda Pani'],
            ['emis' => 750, 'name' => 'IMSG(I-V) DHOK FATHALL', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-21 Tumair'],
            ['emis' => 751, 'name' => 'IMSG(I-V)TUMIAR', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-08 Tumair'],
            ['emis' => 752, 'name' => 'IMSG(I-VIII) KIJNAH', 'gender' => 'girls', 'type' => 'I-VIII', 'sector' => 'Nilore', 'UC' => 'UC-21 Tumair'],
            ['emis' => 753, 'name' => 'IMSG(I-V) SIMLY DAM', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-21 Tumair'],
            ['emis' => 754, 'name' => 'IMSG(I-V) CHIRAH', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-09 Charah'],
            ['emis' => 755, 'name' => 'IMSG(I-V) KALIA', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-24 Chirrah'],
            ['emis' => 756, 'name' => 'IMSG(I-V) JHANG SYEDAN', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-45 Jhangi Saidan'],
            ['emis' => 757, 'name' => 'IMSG (I-V) CHAPPAR Ghasota (F.A)', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-24 Chirrah'],
            ['emis' => 758, 'name' => 'IMSG(I-V) CHAKHTAN', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-24 Chirrah'],
            ['emis' => 759, 'name' => 'IMSG(I-V) NILORE', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-18 Khana Dak'],
            ['emis' => 760, 'name' => 'IMSG(I-V) PUNJGRAN (760)', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-23 Alipur'],
            ['emis' => 761, 'name' => 'IMSG(I-VIII) SOHAN', 'gender' => 'girls', 'type' => 'I-X', 'sector' => 'Nilore', 'UC' => 'UC-21 Sohan'],
            ['emis' => 762, 'name' => 'IMSB(I-V)NILORE', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-18 Khana Dak'],
            ['emis' => 763, 'name' => 'IMSG(I-V) ALI PUR SOUTH', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-20 Alipur'],
            ['emis' => 764, 'name' => 'IMSB(I-V) SIRRI', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-22 Thanda Pani'],
            ['emis' => 765, 'name' => 'IMSG(I-V) FRASH TOWN', 'gender' => 'girls', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-23 Alipur'],
            ['emis' => 766, 'name' => 'IMCG,KIRPA', 'gender' => 'girls', 'type' => 'VI-XII', 'sector' => 'Nilore', 'UC' => 'UC-10 Kirpa'],
            ['emis' => 767, 'name' => 'IMSB(I-V)BIATH', 'gender' => 'boys', 'type' => 'I-V', 'sector' => 'Nilore', 'UC' => 'UC-24 Chirrah'],
            ['emis' => 801, 'name' => 'IMCB, SIHALA, Islamabad.', 'gender' => 'boys', 'type' => 'XI-XII', 'sector' => 'Sihala', 'UC' => 'UC-14 Sihala'],
            ['emis' => 802, 'name' => 'IMPC H-8 ISLAMABAD', 'gender' => 'boys', 'type' => 'XI-XIV', 'sector' => 'Urban-II', 'UC' => 'UC-40 I-8 & H8'],
            ['emis' => 803, 'name' => 'IMCB, F-10/4', 'gender' => 'boys', 'type' => 'XI-XIV', 'sector' => 'Urban-II', 'UC' => 'UC-29 Sector F-10 F-11'],
            ['emis' => 804, 'name' => 'IMCB, H-9', 'gender' => 'boys', 'type' => 'XI-XIV', 'sector' => 'Urban-II', 'UC' => 'UC-41 I-9 & H9'],
            ['emis' => 805, 'name' => 'IMPCC (B), H-8/4', 'gender' => 'boys', 'type' => 'XI-XIV', 'sector' => 'Urban-II', 'UC' => 'UC-40 I-8 & H8'],
            ['emis' => 806, 'name' => 'IMCG (PG), F-7/2,', 'gender' => 'girls', 'type' => 'XI-XIV', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 807, 'name' => 'IMCG(PG), G-10/4,', 'gender' => 'girls', 'type' => 'XI-XIV', 'sector' => 'Urban-II', 'UC' => 'UC-36 Sector G-10/3 G-10/4'],
            ['emis' => 808, 'name' => 'IMCG (MT) Humak', 'gender' => 'girls', 'type' => 'XI-XIV', 'sector' => 'Sihala', 'UC' => 'UC-13 Humak'],
            ['emis' => 809, 'name' => 'IMCG, I-8/3', 'gender' => 'girls', 'type' => 'XI-XIV', 'sector' => 'Urban-II', 'UC' => 'UC-40 I-8 & H8'],
            ['emis' => 810, 'name' => 'IMCG (PG), F-7/4, Islamabad', 'gender' => 'girls', 'type' => 'XI-XIV', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 811, 'name' => 'IMCG I-14/3', 'gender' => 'girls', 'type' => 'XI-XII', 'sector' => 'Tarnol', 'UC' => 'UC-44 Bokra (I-12. H-11 & H-13)'],
            ['emis' => 812, 'name' => 'IMCG (PG) Bharakahu Islamabad', 'gender' => 'girls', 'type' => 'XI-XII', 'sector' => 'B.K', 'UC' => 'UC-04 Kot Hathial (Shamal) Bharakahu'],
            ['emis' => 813, 'name' => 'HE&MC F-11/1', 'gender' => 'girls', 'type' => 'XI-XIV', 'sector' => 'Urban-II', 'UC' => 'UC-29 Sector F-10 F-11'],
            ['emis' => 901, 'name' => 'IMCB, F-10/3', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-II', 'UC' => 'UC-29 Sector F-10 F-11'],
            ['emis' => 902, 'name' => 'IMCB, F-11/1', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-II', 'UC' => 'UC-29 Sector F-10 F-11'],
            ['emis' => 903, 'name' => 'IMCG, F-11/3', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-II', 'UC' => 'UC-29 Sector F-10 F-11'],
            ['emis' => 904, 'name' => 'IMCB, F-7/3', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 905, 'name' => 'IMCB, F-8/4', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 906, 'name' => 'IMCB, G-10/4', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-II', 'UC' => 'UC-36 Sector G-10/3 G-10/4'],
            ['emis' => 907, 'name' => 'IMCB, G-11/1', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-II', 'UC' => 'UC-38 Sector G-11'],
            ['emis' => 908, 'name' => 'ICB G-6/3', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-I', 'UC' => 'UC-27 Sector G-6/2'],
            ['emis' => 909, 'name' => 'IMCB, I-10/1', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-II', 'UC' => 'UC-42 Sector I-10 & H-10'],
            ['emis' => 910, 'name' => 'IMCB, I-8/3', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Urban-II', 'UC' => 'UC-40 I-8 & H8'],
            ['emis' => 911, 'name' => 'IMCCG (COM), F-10/3', 'gender' => 'girls', 'type' => 'XI-XIV', 'sector' => 'Urban-II', 'UC' => 'UC-29 Sector F-10 F-11'],
            ['emis' => 912, 'name' => 'IMCG, ST. 25,  F-6/2', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-I', 'UC' => 'UC-25 Sector F-6'],
            ['emis' => 913, 'name' => 'ICG, F-6/2', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-I', 'UC' => 'UC-25 Sector F-6'],
            ['emis' => 914, 'name' => 'IMCG, F-7/4', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 915, 'name' => 'IMCG, F-8/1', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-I', 'UC' => 'UC-28 F-7 F-8 F-9'],
            ['emis' => 916, 'name' => 'IMCG, G-10/2', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-II', 'UC' => 'UC-37 Sector G-10/1 G-10/2'],
            ['emis' => 917, 'name' => 'IMCG, St. # 23, I-10/4', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-II', 'UC' => 'UC-42 Sector I-10 & H-10'],
            ['emis' => 918, 'name' => 'IMCG, I-8/4', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-II', 'UC' => 'UC-40 I-8 & H8'],
            ['emis' => 919, 'name' => 'IMCG, F-10/2', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Urban-II', 'UC' => 'UC-29 Sector F-10 F-11'],
            ['emis' => 920, 'name' => 'IMCG, Korang Town', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Sihala', 'UC' => 'UC-17 Koral'],
            ['emis' => 921, 'name' => 'IMCG G-13/1', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Tarnol', 'UC' => 'UC-39 Maira Sumbal Jaffar (G-12, G-13)'],
            ['emis' => 922, 'name' => 'IMCG G-14/4', 'gender' => 'girls', 'type' => 'I-XII', 'sector' => 'Tarnol', 'UC' => 'UC-39 Maira Sumbal Jaffar (G-12, G-13)'],
            ['emis' => 923, 'name' => 'IMCB G-13/2', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Tarnol', 'UC' => 'UC-39 Maira Sumbal Jaffar (G-12, G-13)'],
            ['emis' => 924, 'name' => 'IMCB G-15', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Tarnol', 'UC' => 'UC-39 Maira Sumbal Jaffar (G-12, G-13)'],
            ['emis' => 925, 'name' => 'IMCB Pakistan Town', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'Sihala', 'UC' => 'UC-17 Koral'],
            ['emis' => 926, 'name' => 'IMCB Maira Begwal', 'gender' => 'boys', 'type' => 'I-XII', 'sector' => 'B.K', 'UC' => 'UC-07 Pind Begwal'],
        ];
        $sectorCache = [];

        foreach ($schools as $school) {
            $sectorName = $school['sector'];

            // Cache sector lookups
            if (!isset($sectorCache[$sectorName])) {
                $sectorCache[$sectorName] = Sector::where('name', $sectorName)->first();
            }

            $sector = $sectorCache[$sectorName];

            if (!$sector) {
                $this->command->warn("Sector not found: {$sectorName} for school {$school['name']}");
                continue;
            }

            $institution = Institution::firstOrCreate(
                ['code' => (string)$school['emis']],
                    [

                    'name'               => $school['name'],
                    'sector_id'          => $sector->id,
                    'uc_id'              => $sector['uc_id'],
                    'type'               => $school['type'],
                    'gender'             => $school['gender'],
                    'shift'              => 'morning',
                    'admission_status'   => 'not_started',
                    'has_matric_tech'    => false,
                    'has_transport'      => false,
                    'has_meal_program'   => false,
                    'has_evening_classes'=> false,
                    'is_active'          => true,
                ]
            );

            // Set Cambridge flag
            if ($institution->isCambridgeEligible()) {
                \DB::table('institutions')
                    ->where('id', $institution->id)
                    ->update(['is_cambridge' => true]);
            }
        }

        $this->command->info('432 institutions seeded successfully.');
    }
}
